### ISSUE TITLE
Parent's layout properties not taken into account

### ISSUE THREAD

**Issue by xeroxoid** [react-native-community/lottie-react-native#106]
Hi all, first of all great work!

Now I was trying out the library and noticed that the following:

```javascript
...
  render() {
    return (
      <View style={componentStyles.view}>
        <Animation
          style={componentStyles.animation}
          source={require('../animations/dawg.json')}
          loop={true}
        />
      </View>
    );
  }
}

const componentStyles = {
  view: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'green'
  },
  animation: {
    width: 300,
    height: 200,
  }
}
```

produces the following:

![screen shot 2017-03-30 at 13 40 05](https://cloud.githubusercontent.com/assets/1199451/24500708/22e3fc28-154f-11e7-8f60-3f806c0b979a.png)

**Comment by ochanje210** [comment]
having same issue here.

**Comment by Vasiliev90** [comment]
+1

**Comment by Vasiliev90** [comment]
found a solution:  to wrap animation in View with the same width and height and align it, not Animation

**Comment by mesbahsabur** [comment]
+1

@Vasiliev90  nice workaround!

Btw, I suggest an [iOS] label here, this issue does not effect Android.

**Comment by cinder92** [comment]
same issue here! is related to mine! #135

**Comment by cinder92** [comment]
@mesbahsabur same issue is happening on android, son both labels please

**Comment by cinder92** [comment]
we can use a transform styling, but seems to be pixelated :(

**Comment by henrikra** [comment]
@Vasiliev90 This indeed works! I think this should be added to the README. Or even better make it so that `Animation` always renders `View`

**Comment by RyanMitchellWilson** [comment]
Still getting this problem but the workaround is working for now.

**Comment by chenpengfei88** [comment]
看不懂啊

**Comment by gmac13** [comment]
I'm still having this problem even when i wrap the animation in a view with the same height and width, here's what i have 

` <View
          style={{
            alignItems: 'center',
            width: 60,
            height: 60,
            position: 'absolute'
          }}
        >
          <Animation
            style={{
          
              width: 60,
              height: 60
            }}
            source={require('./img/menuButton1.json')}
          />
        </View>`

Anyone have any suggestions, thanks.

**Comment by vaxxis** [comment]
@gmac13 you probably need to remove the alignItems and position properties, create another containing View for that.

try this:
```jsx
<View style={{ alignItems: 'center', width: 60, height: 60, position: 'absolute' }} >
  <View style={{ width: 60, height: 60 }}>
    <Animation style={{ width: 60, height: 60 }} source={require('./img/menuButton1.json')} /> 
  </View>
</View>
```

**Comment by Gringox** [comment]
I agree with @mesbahsabur, I found this issue only happening on iOS

**Comment by simonmitchell** [comment]
@emilioicai I have a fix for this, here: https://github.com/3sidedcube/lottie-react-native/commit/849d1f9a89824a0f654f68fb645bff4e406c4a29. Unfortunately it seems your master has come on a long way since then and we have merge conflicts which we need to fix before I can create a PR. I'm also unsure of any other knock-on effects this could have!

**Comment by emilioicai** [comment]
@simonmitchell it would be great if you could issue a PR, I can support you with the conflicts fixes in case you find it to complex.
