### ISSUE TITLE
FPS seems to drop a lot while displaying multiple instances of an animation

### ISSUE THREAD

**Issue by ranjithnori** [react-native-community/lottie-react-native#133]
We are facing huge FPS drops when we display multiple instances of a lottie animation. 

To replicate this, try to display 6-7 instances of the following animation, you can see that FPS drops to around 4-5 on both JS and UI threads.
Animation file: https://www.lottiefiles.com/236-accept-arrows

Are we missing something here ? What can be done to prevent this ?

Thanks in advance

**Comment by gpeal** [comment]
@ranjithnori Can you attach a sample project that repros this? I can't reproduce this.
There have also been many lottie updates since this that have improved performance quite a bit.

**Comment by ranjithnori** [comment]
@gpeal We've reproduced this on the example app provided in this repo. The animation contains a few  image files as well. We're trying to display a single instance of this animation.
The FPS drops to around 7-10 both on the JS and UI threads.

Can you provide us with your e-mail address ? We'll DM you the link to the repo since it contains some proprietary images.

**Comment by JakeRawr** [comment]
Hi, 

@gpeal I'm also having problem with FPS dropping. In my case, I have 14 <Lottie /> loading at the same time and all of them have images files in it. The FPS seems to only resume when all Lottie components are finish loading

**Comment by oferRounds** [comment]
Seeing this also, has anyone found any workaround to this?

**Comment by oferRounds** [comment]
Getting this also on latest version (3.0.1)

**Comment by oferRounds** [comment]
@ranjithnori have you found any solution to this?

**Comment by emilioicai** [comment]
ios or android? if it's android you could try with the latest version which uses lottie-android 3.0.0

**Comment by oferRounds** [comment]
iOS.... with React Native‘s FlatList

**Comment by oferRounds** [comment]
One instance works perfect, more than one – scrolling getting not smooth

**Comment by ranjithnori** [comment]
> @ranjithnori have you found any solution to this?

@oferRounds I didn't find any solutions for this

**Comment by oferRounds** [comment]
@ranjithnori got you, thanks!

@gpeal - any idea how can we workaround this one?

**Comment by oferRounds** [comment]
Can this get reopened please?

**Comment by brandtnewww** [comment]
I also experience this - https://github.com/react-native-community/lottie-react-native/issues/582

**Comment by muhammadwafa** [comment]
Same issue with the latest version 300 dropped so far only in 5 seconds
