### ISSUE TITLE
java.lang.IllegalStateException: You must set an images folder...

### ISSUE THREAD

**Issue by lappalj4** [react-native-community/lottie-react-native#153]
Hey, 

thanks for the library - it looks very promising!

I'm seeing a crash on android, where the animation will begin to play but after a second or two the app will crash with the following logcat output:

````
07-15 21:16:32.668  3673  3690 W LOTTIE  : Lottie doesn't support layer effects. If you are using them for  fills, strokes, trim paths etc. then try adding them directly as contents  in your shape.
07-15 21:16:32.884  3673  3673 W LOTTIE  : Composition larger than the screen 5040x2835 vs 1080x1794. Scaling down.
07-15 21:16:33.879  3673  3673 D AndroidRuntime: Shutting down VM
07-15 21:16:33.963  3673  3673 E AndroidRuntime: FATAL EXCEPTION: main
07-15 21:16:33.963  3673  3673 E AndroidRuntime: Process: ch.enluf.laaxexplore, PID: 3673
07-15 21:16:33.963  3673  3673 E AndroidRuntime: java.lang.IllegalStateException: You must set an images folder before loading an image. Set it with LottieComposition#setImagesFolder or LottieDrawable#setImagesFolder
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.ImageAssetManager.bitmapForId(ImageAssetManager.java:73)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:510)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.ImageLayer.getBitmap(ImageLayer.java:57)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.ImageLayer.getBounds(ImageLayer.java:41)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.CompositionLayer.getBounds(CompositionLayer.java:101)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.BaseLayer.intersectBoundsWithMatte(BaseLayer.java:295)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.BaseLayer.draw(BaseLayer.java:184)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.CompositionLayer.drawLayer(CompositionLayer.java:87)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.BaseLayer.draw(BaseLayer.java:175)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:305)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.widget.ImageView.onDraw(ImageView.java:1244)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.draw(View.java:16178)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.buildDrawingCacheImpl(View.java:15474)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.buildDrawingCache(View.java:15335)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.draw(View.java:15941)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.draw(View.java:16181)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15174)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:15134)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
07-15 21:16:33.963  3673  3673 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:60
````

Question is, is this crash happening because the animation is using unsupported layer effects as the first line indicates, or is it something else? Will have to wait until our designer is able to create an animation that is completely supported, but in the meantime I figured I might ask around here. Thanks!

Specs:
lottie-react-native 1.2.0
Google Nexus 5X 6.0.0 emulator running API 23

**Comment by lappalj4** [comment]
Update: tried with an animation that does not have any layer effects, and the same error is still occurring - minus the warning on the first line. Can anyone help with this?

**Comment by lappalj4** [comment]
Apparently it is an issue with using external images in the animation. Has anyone found out how to use external images and where to put them on android/ios?

**Comment by dioxide** [comment]
same problem

**Comment by Shagamii** [comment]
I think could be linked to https://github.com/airbnb/lottie-android/issues/235

In my case, I resolved to adjust "assets"  value in json to be output empty.

**Comment by Jiansion** [comment]
I encountered same problem.
Because loading image must be set image folder.
such as  In Assets create image folder save image

`
        LottieAnimationView lottieAnimationView = (LottieAnimationView) findViewById(R.id.animation_view);
        lottieAnimationView.setImageAssetsFolder("images/");
        lottieAnimationView.setAnimation("splash_animation.json");
        lottieAnimationView.loop(false);
        lottieAnimationView.playAnimation();
`

**Comment by lappalj4** [comment]
@Shagamii thanks, will have a look if that resolves the issue

**Comment by createS0ftware** [comment]
@lappalj4 Did you solve this issue ? Thanks

**Comment by lappalj4** [comment]
@createS0ftware nope, sorry. Ended up having our designer export animations that have no external assets. I'm not familiar with bodymovin, but apparently you can force it to export .json files that have no external dependencies if you tweak the configuration.

**Comment by m-akopov** [comment]
Has anyone idea how fix this ? @lappalj4  I can't find out how to force bodymovin to export in one json file. And my animation doesn't load itself, white view :(

**Comment by wilson100** [comment]
Just set up this prop specific to Android:
  `imageAssetsFolder: string,`

Read about it in Lottie docs for RN:
http://airbnb.io/lottie/react-native/props.html

**Comment by gpeal** [comment]
@lappalj4 @m-akopov If you have Illustrator layers or anything like that, make sure to convert them to shape layers. More info [here](http://airbnb.io/lottie/after-effects/artwork-to-lottie-walkthrough.html). Images should be seldomly needed for Lottie and you lose a lot of the benefits of Lottie when you use them.

**Comment by schumannd** [comment]
Why is this issue closed? The crash still occurs on the latest lottie version

**Comment by emilioicai** [comment]
@schumannd did you try @gpeal's recommendation?

**Comment by schumannd** [comment]
@emilioicai, I still think this issue should stay open as long as it causes native crashes. Maybe the crash can be caught and converted into a proper JS Error with the Error message?

**Comment by emilioicai** [comment]
@schumannd  agreed, I'm reopening

**Comment by keivanshamlu** [comment]
this happens when your animation has "images" folder and you didnt place it in your assets folder.
"images" folder contains images of your  animation that couldnt convert to json object ,so it refrensed in json code to that particular image , when you dont place this folder, animation is incomplete and it will crashes your app .

**Comment by RoJoHub** [comment]
> 当您的动画有“images”文件夹并且您没有将它放在您的资源文件夹中时会发生这种情况。
> “images”文件夹包含无法转换为json对象的动画图像，因此它在json代码中反映到该特定图像，当您不放置此文件夹时，动画不完整并且会崩溃您的应用程序。

You're right.So i edit the data.json.
delete `assets ` and `refId`
----
For example 

```
"assets":[{"id":"image_0","w":48,"h":68,"u":"images/","p":"img_0.png","e":0},{"id":"image_1","w":64,"h":64,"u":"images/","p":"img_1.png","e":0},{"id":"image_2","w":280,"h":180,"u":"images/","p":"img_2.png","e":0}]
```

```
"refId":"image_0"
"refId":"image_1"
"refId":"image_2"
```

**Comment by schumannd** [comment]
@RoJoHub wouldn't deleting `assets` form the json break the whole file? It seems to make up >50% of the file content for me

**Comment by RoJoHub** [comment]
> @RoJoHub wouldn't deleting `assets` form the json break the whole file? It seems to make up >50% of the file content for me

If the designer uses image, I think that can't delete assets.

I didn't use the image in my animation. So I deleted it.

**Comment by ged204** [comment]
I'm having this issue but with json where assets is an empty array and deleting it made no difference.

**Comment by mingxin-yang** [comment]
You can find the solution in this. https://github.com/react-native-community/lottie-react-native/blob/6adef35bdecdaf8157486e875fb324a8ee158e5d/docs/api.md#using-animations-with-assets

**Comment by ThakurKarthik** [comment]
> You can find the solution in this. https://github.com/react-native-community/lottie-react-native/blob/6adef35bdecdaf8157486e875fb324a8ee158e5d/docs/api.md#using-animations-with-assets

This worked for me in my case.

**Comment by schumannd** [comment]
Why was this closed? It seems like people are running into this crash still. (see #542)

**Comment by parth-choudhary** [comment]
To resolve this, create a native assets folder (for android `app/src/main/assets`).
Place your images inside a folder in this assets folder (like `app/src/main/assets/images`).

Now in the `LottieView` add a prop `imageAssetsFolder`, that should do it.
Final code: 
`<LottieView source={require('../assets/..some.json')} imageAssetsFolder={'images'} autoPlay  />`

**Comment by Jalcaraz0** [comment]
is there a way to catch the crash without create the native asset folder?

**Comment by linleiqin** [comment]
The best way to solve this problem is to include Images in the json file.
In the export settings of the Bodymovin plugin in After Effects software, you can find the "Include in json" option. The specific steps are as follows:

In After Effects, select the Window menu, then select Extensions -> Bodymovin.

In the Bodymovin panel, select the animation you want to export.

Click the setting icon (Render Setting) on the right to open the setting dialog box.

In the pop-up setting dialog box, you will see the "Assets" tab.

In the "Assets" tab, find and check "Include in json".

Click "OK" to save the settings and then proceed with the export.
