### ISSUE TITLE
Feature request: Dynamic re-coloring

### ISSUE THREAD

**Issue by JulianKingman** [react-native-community/lottie-react-native#180]
It looks like both the iOS and Android versions of Lottie support some sort of recoloring:
http://airbnb.io/lottie/android/colors.html
http://airbnb.io/lottie/ios/dynamic.html
It would be cool to see that on react native. I'm not sure if this is how it works, but it could possibly be as easy as making a helper tool that modifies the JSON source directly.

**Comment by chensara** [comment]
Is someone working on this issue?

**Comment by grabbou** [comment]
Yes, please. I would be happy to contribute this feature - do you have an idea what the API could look like?

**Comment by zachgibson** [comment]
@grabbou Something similar to the Android interface seems like it would work well.

Color all the layers:
```JSX
<LottieView
  source={require('../path/to/animation.json')}
  progress={this.state.progress}
  colorFilter="#bae"
/>
```
or Color specific layer:
```JSX
<LottieView
  source={require('../path/to/animation.json')}
  progress={this.state.progress}
  colorFilterForLayer={{ layer: 'some_layer', colorFilter: '#bae' }}
/>
```

**Comment by carmenchapa** [comment]
Any update on this?

**Comment by fantasy525** [comment]
Any update on this?

**Comment by HonzaJiran** [comment]
Just please :'----(
