### ISSUE TITLE
Failed to resolve: com.android.support:appcompat-v7:26.1.0

### ISSUE THREAD

**Issue by Shariaty** [react-native-community/lottie-react-native#256]
After installing lottie-react-native based on the docs I get this error
**Error:Failed to resolve: com.android.support:appcompat-v7:26.1.0**

and i add 'https://maven.google.com'
```
allprojects {
    repositories {
        maven {
            url 'https://maven.google.com'
        }
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```
to my project build.gradle

But there is no luck.. still i get 
**Error:Failed to resolve: com.android.support:appcompat-v7:26.1.0**

**Comment by shaksi** [comment]
there should be compile "com.android.support:appcompat-v7:" in your android/app/build.gradle.

change its number to 26.0.1 so that the compile line is `compile "com.android.support:appcompat-v7:26.0.1"`

make sure to set the compile and build tools version to the same (at the top of the same file):

```
compileSdkVersion 26
buildToolsVersion "26.0.1"
```

**Comment by alexsmartens** [comment]
+1 I'm having the same problem

**Comment by Shariaty** [comment]
+1 i still cannot get this worked !!

**Comment by axlalvaro** [comment]
@Shariaty @alexsmartens I found the solution here: https://github.com/airbnb/lottie-react-native/issues/203

**Comment by alexsmartens** [comment]
@axlalvaro thank you. 
It did not helped me though. I got the following error afterwards:

```
:lottie-react-native:generateReleaseBuildConfig FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lottie-react-native:generateReleaseBuildConfig'.
> java.io.IOException: Could not delete path 'D:\myPATH\myApp\node_modules\lottie-react-native\src\android\build\generated\source\buildConfig\release\com\airbnb'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Did you see anything like that?

**Comment by axlalvaro** [comment]
@alexsmartens No, sorry. The only changes I made were:

In my app build.gradle:
`android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"`

In my project build.gradle:
`allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}`

**Comment by p1xedge** [comment]
i have same problem i tried this 

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

**Comment by manojMadarasingha** [comment]
Try adding a more stable version such as V 26.0.0

**Comment by AnisDerbel** [comment]
+1
