### ISSUE TITLE
size of animation larger than 480?

### ISSUE THREAD

**Issue by badtant** [react-native-community/lottie-react-native#260]
Hi,

I'm just getting started with Lottie (I'm using Expo) and have some trouble with the size of my animation. When I set the size larger than 480 it wont render. Is there a limit?

This is the animation I'm using:
https://www.lottiefiles.com/347-like

```
import React from 'react';
import {StyleSheet} from 'react-native';
import {DangerZone} from 'expo';
const {Lottie} = DangerZone;

import animation from './lottieJson/like';

export default class LottieTest extends React.Component {
    componentDidMount() {
        this.animation.play();
    }

    render() {
        return (
            <Lottie
                ref={animation => {
                    this.animation = animation;
                }}
                style={styles.container}
                source={animation}
                loop
            />
        );
    }
}

const styles = StyleSheet.create({
    container: {
        width: 400,
        height: 400
    }
});
```

**Comment by fjtrujy** [comment]
Hello,
I have exactly the same problem do you have any news?

Thanks!

**Comment by badtant** [comment]
I now use this lib to include my animations: https://www.npmjs.com/package/easy-lottie-react-native

And then I use this style to zoom:
```
transform: [
   { scale: 3.3 }
]
```

**Comment by emilioicai** [comment]
`easy-lottie-react-native` was long time ago merged with `lottie-react-native` and deprecated
