### ISSUE TITLE
Dynamic colors

### ISSUE THREAD

**Issue by hamdiwanis** [react-native-community/lottie-react-native#268]
Can't we have dynamic colors changes like this in android airbnb/lottie-android#504 , and this on ios airbnb/lottie-ios#236 , it would be a great feature to have . Thanks

**Comment by emilioicai** [comment]
@hamdiwanis that sounds great to me, would you have the time to create a PR for this?

**Comment by peterpojuner** [comment]
Anyone know if this PR was ever created ?

**Comment by emilioicai** [comment]
This is a related PR:

https://github.com/react-native-community/lottie-react-native/pull/584

**Comment by hamdiwanis** [comment]
@peterpojuner I did make it and not color only but dynamic properties but it was rejected https://github.com/react-native-community/lottie-react-native/pull/427
