### ISSUE TITLE
Dynamic properties support

### ISSUE THREAD

**Issue by jozan** [react-native-community/lottie-react-native#275]
Now that dynamic properties are supported both in `lottie-ios` and `lottie-android` are there any plans to bring those to `lottie-react-native`?

How can I help?

**Comment by gpeal** [comment]
@jozan Due to the synchronous nature of dynamic properties, I haven't figured out a feasible way to make this happen. Any ideas?

**Comment by nextriot** [comment]
Generator functions?

**Comment by gpeal** [comment]
@nextriot How would that work? Sorry, I'm not familiar with those.

**Comment by emilioicai** [comment]
@jozan would you be interested in creating a PR for this? I agree generator functions could be a nice approach

**Comment by jozan** [comment]
Unfortunately I don’t have any time for this project in the foreseeable
future. :)

**Comment by GoMino** [comment]
Hello @emilioicai, Why closing the issue ?

**Comment by emilioicai** [comment]
Hi @GoMino , there was nobody willing to implement this enhancement but if you think it's still doable I will reopen

**Comment by arasrezaei** [comment]
+1 for this!
