### ISSUE TITLE
remote uri

### ISSUE THREAD

**Issue by ganap** [react-native-community/lottie-react-native#287]
I tried using along the following lines, but it doesn't render the animation. I am using it as follows

<LottieLoader source= {{uri: <path + filename.json>}}/> 

However, if I reference the file locally using require(<path/filename>), it works fine. Couldn't find an example to do this. 

Does the remote uri option work?

**Comment by tafelito** [comment]
I don't think it's possible to do this right now, but it would be great to be able to do it, specially loading images from a url. For the json file I imagine you could manually fetch the file and then load the animation

**Comment by animaonline** [comment]
Here's what the documentation says:

```
The source of animation. Can be referenced as a local asset by a string, or remotely
     * with an object with a `uri` property
```

Shouldn't it be able to load remote files then?

**Comment by kallrobin** [comment]
Any update on this? I'm using the same syntax as ganap but i can't get it to work.
this is the obj i'm passing to Lottie.
> {uri: "https://www.theanimation.com/animation.json"}

**Comment by tresdev** [comment]
Can't get it to work. it should be working, right?

**Comment by emilioicai** [comment]
@tresdev do you get any errors?

**Comment by visopsys** [comment]
I can make it work either. I cannot load animation from local SD card. The value I pass in is:
```
uri: file:///storage/emulated/0/example.json
```
The `file:///` pattern works with React Native Image.

**Comment by davidboll** [comment]
Any update on this?

**Comment by barghi** [comment]
Any Update ?

**Comment by emilioicai** [comment]
This is working for me. Is it possible the app cannot reach the JSON file? Maybe the url the file is in is not whitelisted on NSAppTransportSecurity.

For anyone seeing this bug, is this on Android, iOS or both?

**Comment by barghi** [comment]
hi @emilioicai 
I have faced with this problem in Android
could you please test this file and say if it works or not ?
https://cdn.bazambazi.com/emote/emote_free_arm.json

**Comment by barghi** [comment]
Hi @emilioicai 
I have faced with this problem in **Android**.

Could you please test this file and say if it works or not ?
[https://cdn.bazambazi.com/emote/emote_free_arm.json](url)

I can fetch the JSON file with **FetchBlob**.
in other hand i want to save file in the **cache** and read it later
and i don't know where can i save the file.

 url file in cache (saved with fetchBlob):
```
file:///data/user/0/com.bazambazi.debug/cache/emote_emote_free_arm.json
```

**Does not work**  ```<LottieView source={{ uri: remotePath }} />```
**Does not work** ```<LottieView source={{ uri: cachedPath }} />```
**Does not work** ```<LottieView source={cachedPath} />```
**works Perfectly** ```<LottieView source="BundledJson" />```


Thanks

**Comment by barghi** [comment]
Hi Again

We have fixed the problem with this approach :

```
RNFetchBlob.fs.readFile(localJsonPath, 'utf8')
     .then((data) => {
          this.setState({
             jsonPath: JSON.parse(data)
          });
     });
```

and the component :
```
{this.state.jsonPath ?
    <LottieView source={this.state.jsonPath} />
: null}
```

**Comment by emilioicai** [comment]
There's indeed an issue with the remote urls, I will keep this issue open for the time being and investigate a bit further.

**Comment by s349856186** [comment]
Any Update ? @emilioicai

**Comment by emilioicai** [comment]
unfortunately I didn't make any progress on this yet :(

**Comment by Cawfree** [comment]
Same here, although there's  manual workaround where you can use something like [`axios`](https://github.com/axios/axios) to download the JSON manually and supply it as the `source` directly. I'm not convinced this is an ideal solution because your `state` will grow quite large.

**Comment by ThakurKarthik** [comment]
Same for me,Error while loding through url.
![Error](https://user-images.githubusercontent.com/26309938/64925917-f4d42480-d814-11e9-8a1a-49bc1b0f0650.png)

**Comment by muhammadwafa** [comment]
@ThakurKarthik Same error here when using source={{uri: https://somewebsite.com/lottiefile.json}}

**Comment by muhammadwafa** [comment]
@barghi , I used your solution, but it generate this error:

`SyntaxError: JSON Parse error: Property name must be a string literal`

**Comment by s349856186** [comment]
@emilioicai This issue is closed Is the new version resolved or abandoned?

**Comment by emilioicai** [comment]
@s349856186 it seems lottie-android won't support this feature so I closed this issue until we decide if we have to support iOS only or completely ditch the prop.

**Comment by Foskas** [comment]
Hi all,

Do we have any updates on this ? @emilioicai 

Thanks!

**Comment by balumuriraj** [comment]
Any update on this?

**Comment by JmStefanAndroid** [comment]
same error !!

**Comment by nescroft** [comment]
The uri info should be removed from the documentation since it doesn't work. I just wasted time trying to figure it out.

**Comment by DAAI093** [comment]
meet the same problem，i think if its not support uri, it shouldn't be write in the document

**Comment by Rajan-Savaliya-spt** [comment]
` <LottieView source={jsonObject} />`
work for me......

**Comment by thechaudharysab** [comment]
`<LottieView source={{uri: 'https://assets1.lottiefiles.com/private_files/lf30_GjhcdO.json'} autoPlay loop />` does not work!

**Comment by baronha** [comment]
> `<LottieView source={{uri: 'https://assets1.lottiefiles.com/private_files/lf30_GjhcdO.json'} autoPlay loop />` does not work!

same me 
+ 1

**Comment by cengit** [comment]
this works for me
```ts
fetch('http://example.com/movies.json')
  .then(response => response.json())
  .then(data =>this.setState({slideData:data}));

<LottieView source={this.state.slideData} autoPlay loop />
```

**Comment by CanniJr** [comment]
@cengit 

I used hooks for this and it works! (I'm on expo)
Tried uri, and it's still not working. 
```
const [lottie, setLottie] = useState("");

  useEffect(() => {
    fetch("https://somesite.com/file.json")
      .then((resp) => resp.json())
      .then((data) => setLottie(data));
  }, []);

<LottieView source={lottie} autoPlay loop  />
```

**Comment by alexi-stein** [comment]
Still having this issue. Think it should be reopened or at the very least removed from the docs. The json workaround fails if you are using image assets relative to the remote json file.

**Comment by ceejae-cashew** [comment]
The uri works. You need to set a width and height for it to render.

**Comment by stanjhae** [comment]
The uri works. You need to set a width and height so it can render.

**Comment by abhayu0** [comment]
There are 2 link you will get from lottie, when you download any animation-

Asset URL - https://lottie.host/d105d348-0df3-4358-801b-93edc39fdd3d/wcjEqHLXW3.json
Embed URL - https://lottie.host/d105d348-0df3-4358-801b-93edc39fdd3d/wcjEqHLXW3.json

You need to use the asset URL, it will work. Hope this help.

**Comment by ThisaraFcode** [comment]
> The uri works. You need to set a width and height so it can render.
> 
> Hope this saves someone hours of debugging and unnecessary work arounds.

you saved my day. it is working, simply not showing without width and height
