### ISSUE TITLE
lottie framework not found in xcode project follow official guide, please add manual link option 

### ISSUE THREAD

**Issue by elanpang** [react-native-community/lottie-react-native#323]
I met a strange issue.
I start a react-native project with react-native 0.55.2, then setup lottie and do everything follow the official guide,
first npm install , 
then use react-native link or pod install to add framewok, (tried many times with different ways )
pod install sucessful or link sucessful, but I still **can't find framework in xcode project**

I already install/uninstall  link/unlink many times, but I still can't find lolitte.framework or child xcode project in libraries folder, so I also can't make it be Embedded Binaries and still can't use it.

Is there anyone with the same issue ?

**Comment by breadadams** [comment]
I _think_ I may have ran into something similar when adding the lib to a project recently.

Have you tried following the steps [here](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) for a "manual link"? Ie. dragging lottie files from your projects `node_modules` into Xcode.

**Comment by mysport12** [comment]
@elanpang I too was unable to get it to work going the Pods route. Try manually linking the projects as @breadadams suggested and then under the General tab add Lottie.framework.

**Comment by elanpang** [comment]
@breadadams @mysport12  yes, the "manual link" works, and I also found some similar issues in other components that you have to manual link , thank you very much !

**Comment by breadadams** [comment]
I _am_ interested in why the CocoaPods setup doesn't work though. We've got other libs linked that way working without fail, however Lottie wasn't _recognised_ it seems.

For us there were no errors on build time, just simply a "blank canvas", after doing the manual link everything worked 100% as expected.

**Comment by elanpang** [comment]
I feel confuse and also be interested in it,  I met the same issue in react-native-interactable.

But anyway, I think the official guide should add manual link option to their guide doc or troubleshooting  page

**Comment by jayesbe** [comment]
Manual linking worked for me as well
Had to manual link `libLottie.a` and `libLottieReactNative.a` under General -> Linked Frameworks and Libraries.

**Comment by seblau** [comment]
@breadadams: Could you find a solution for the installation via cocoapods? I am having the same issue, see: https://github.com/airbnb/lottie-react-native/issues/344

**Comment by mversteeg3** [comment]
I had the same problem as above, fixed by adding LottieLibraryIOS and LottieReactNative to "TargetDependencies" in "Build Phases"

**Comment by schumannd** [comment]
I feel like there was a more comprehensive guide in the readme some time ago. Now I just find the single sentence

 `After this, open the Xcode project configuration and add the Lottie.framework as Embedded Binaries.`

**Comment by emilioicai** [comment]
@schumannd Any chance you could help me building a better README? It would be great to have the point of view of a critic user

**Comment by nlwiskus** [comment]
@emilioicai unfortunately my team can't use react native link, so if anyone else wants to manually install it (RN 0.57 btw), this is how I did it.

1. From your `./node_modules/lottie-ios/` take the `Lottie.xcodeprioj` and drag it into your Xcode project under the `Library` folder.

2. Do the same thing with the project file in `./node_modules/lottie-react-native/src/ios/`

3. In your libraries, expand the `LottieReactNative.xcodeproj` and `Lottie.xcodeproj` 
 - in `LottieReactNative/Products/` take the `libLottieReactNative` and drag it into *Link Binary With Libraries* under `Build Phases`.
- in `Lottie/Products` things get a little weird, there was two `libLottie.a` files.. I dragged both in and (after step four) I compiled and it failed, turning one of the `libLottie.a` red, so I removed the links for both and dragged the non-red one in. 

4. Go to the *Build Settings* tab and search `header search path`, expand the value and add in the two search paths to the libraries. Mine were: 
`$(SRCROOT)/../node_modules/lottie-react-native/src/ios` (non-recursive)
`$(SRCROOT)/../node_modules/lottie-ios` (non-recursive)

5. Compile! I hope that helped, here is the documentation for manually linking packages to ios: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

**Comment by emilioicai** [comment]
@nlwiskus great! I will add this to the README

**Comment by tokinonagare** [comment]
@nlwiskus awesome! 😄

**Comment by Alenius** [comment]
I still get:

`Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`

even after following @nlwiskus advice step-by-step. 

Anyone else with this problem?

**Comment by bigggge** [comment]
@Alenius same issue
