### ISSUE TITLE
All animations play at the same time in the flatlist

### ISSUE THREAD

**Issue by AwesomeKiddo** [react-native-community/lottie-react-native#330]
I want to play animations individually once clicked on. For some reason when I click even one of them, all of them play.

Here is my code: 
anim_star = (id) => {
  Alert.alert(id);
  let progress = this.state.progress;
  progress[id] = new Animated.Value(0);
//  Alert.alert(progress);
  this.setState({ progress });
  Animated.timing(this.state.progress[id], {
    toValue: 1,
    duration: 2000,
    easing: Easing.linear,
  }).start();
 }

<FlatList

       data={ this.state.dataSource}

       ItemSeparatorComponent = {this.FlatListItemSeparator}

       renderItem={({item}) => <View>

       <Card>

         <View>
         <TouchableOpacity
         onPress={this.anim_star.bind(this, item.id)}
          style={{position:'absolute',  height: '100%', width: '100%',}}>
          <Animation
          progress={this.state.progress[item.id]}
          source={require('../Animations/favourite_app_icon.json')}
          style={{ height: '100%', width: '100%', position: 'absolute'}}
          resizeMode={`contain`}

          />
          </TouchableOpacity>

         </View>

       </Card>

       </View>

     }

     keyExtractor={(item, index) => index.toString()}
     removeClippedSubviews

  />

Also to note, the id is indeed passing through the function and I can alert the correct id that I clicked on.

**Comment by emilioicai** [comment]
closed due to inactivity
