### ISSUE TITLE
android animation still crash

### ISSUE THREAD

**Issue by pohsiu** [react-native-community/lottie-react-native#339]
lottie version: 2.5.0
react native: 0.55
react : 0.16

everything works fine on ios
I also follow the guide then build up
Still crash for no reason , 
But add style={{}} props could build up but animation still not showing,
Same issue on 2.3.0, 2.2.7, 2.2.0

**Comment by pohsiu** [comment]
I used example project build up fine but got this error

```
Starting: Intent { cmp=com.example/.MainActivity }
Error type 3
Error: Activity class {com.example/com.example.MainActivity} does not exist.
```

**Comment by leonardoballand** [comment]
Same here :(

**Comment by schumannd** [comment]
Turns out the crash was caused by issue #153

I think as some RN users don't know how to debug native crashes, this native crash should be caught and a proper error message should be displayed in JS context.
