### ISSUE TITLE
Two motion not play in a view by changing state

### ISSUE THREAD

**Issue by AmirHosseinSalari** [react-native-community/lottie-react-native#340]
Hi,I've two json file as individual motion and actually I want to show both of them in a view by changing state but when I change the state of page the motions stop playing.Actually they show but not play.
pleeeeeeeeeease help me!

**Comment by ali226281** [comment]
hi , you can use an array for save address of  json files and load one of them by condition for example:
in constructor ...
`this.array=[require('./1.json'),require('./2.json')];` 
and load by condition:
`source={this.state.flag ? this.array[0]:  this.array[1]}`

**Comment by s349856186** [comment]
@ali226281  The animation still stop when source had changed. How can I fix it?

@AmirHosseinSalari  Have you solved it?

**Comment by s349856186** [comment]
@emilioicai same issue， Can you help me？

**Comment by emilioicai** [comment]
@s349856186 this is Android specific, right? can you try with the latest version of `lottie-react-native`? It includes native changes so you will need to clean and re-link.

**Comment by s349856186** [comment]
@emilioicai ios have same issue

**Comment by s349856186** [comment]
@emilioicai I hope to hear from you, is the reason for this question confirmed?
Are there any temporary measures to fix? Thank you very much

**Comment by emilioicai** [comment]
@s349856186 I'm still looking into this issue but it would be very helpful if you could share some code as I'm not able to reproduce.

**Comment by s349856186** [comment]
@emilioicai 
Left.json:
{"assets":[],"layers":[{"ddd":0,"ind":0,"ty":4,"nm":"“right”profile","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":25,"s":[0],"e":[100]},{"t":51}]},"r":{"k":0},"p":{"k":[1600.5,421,0]},"a":{"k":[768.5,421,0]},"s":{"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":{"i":[[1.571,12.855],[7.857,7.856],[0,0],[16.917,-16.917],[-16.918,-16.918],[0,0],[0,0],[-16.918,-16.917],[-16.917,16.918],[0,0]],"o":[[-0.559,-10.344],[0,0],[-16.918,-16.917],[-16.918,16.918],[0,0],[0,0],[-16.918,16.917],[16.917,16.918],[0,0],[9.813,-9.813]],"v":[[156.527,-3.861],[143.909,-32.24],[-79.662,-255.812],[-141.18,-255.812],[-141.18,-194.293],[53.247,0.134],[-140.913,194.294],[-140.913,255.812],[-79.395,255.812],[144.176,32.241]],"c":true}},"nm":"path 2","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.83,0.45,0.08,1]},"o":{"k":100},"nm":"fill 2","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[340.484,420.945],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"convert"}],"nm":"group 2","np":2,"mn":"ADBE Vector Group"}],"ip":0,"op":750,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":2,"ty":4,"nm":"“right”profile","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":0,"s":[0],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":29,"s":[100],"e":[0]},{"t":51}]},"r":{"k":0},"p":{"k":[1176.5,421,0]},"a":{"k":[768.5,421,0]},"s":{"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":{"i":[[1.571,12.855],[7.857,7.856],[0,0],[16.917,-16.917],[-16.918,-16.918],[0,0],[0,0],[-16.918,-16.917],[-16.917,16.918],[0,0]],"o":[[-0.559,-10.344],[0,0],[-16.918,-16.917],[-16.918,16.918],[0,0],[0,0],[-16.918,16.917],[16.917,16.918],[0,0],[9.813,-9.813]],"v":[[156.527,-3.861],[143.909,-32.24],[-79.662,-255.812],[-141.18,-255.812],[-141.18,-194.293],[53.247,0.134],[-140.913,194.294],[-140.913,255.812],[-79.395,255.812],[144.176,32.241]],"c":true}},"nm":"path 2","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.83,0.45,0.08,1]},"o":{"k":100},"nm":"fill 2","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[340.484,420.945],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"convert"}],"nm":"group 2","np":2,"mn":"ADBE Vector Group"}],"ip":0,"op":750,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":4,"ty":4,"nm":"“right”profile","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":0,"s":[100],"e":[0]},{"t":27}]},"r":{"k":0},"p":{"k":[768.5,421,0]},"a":{"k":[768.5,421,0]},"s":{"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":{"i":[[1.571,12.855],[7.857,7.856],[0,0],[16.917,-16.917],[-16.918,-16.918],[0,0],[0,0],[-16.918,-16.917],[-16.917,16.918],[0,0]],"o":[[-0.559,-10.344],[0,0],[-16.918,-16.917],[-16.918,16.918],[0,0],[0,0],[-16.918,16.917],[16.917,16.918],[0,0],[9.813,-9.813]],"v":[[156.527,-3.861],[143.909,-32.24],[-79.662,-255.812],[-141.18,-255.812],[-141.18,-194.293],[53.247,0.134],[-140.913,194.294],[-140.913,255.812],[-79.395,255.812],[144.176,32.241]],"c":true}},"nm":"path 2","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.83,0.45,0.08,1]},"o":{"k":100},"nm":"fill 2","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[340.484,420.945],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"convert"}],"nm":"group 2","np":2,"mn":"ADBE Vector Group"}],"ip":0,"op":750,"st":0,"bm":0,"sr":1}],"v":"4.5.3","ddd":0,"ip":0,"op":51,"fr":25,"w":1537,"h":842}


Right.json:
{"assets":[],"layers":[{"ddd":0,"ind":0,"ty":4,"nm":"“right”profile","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":25,"s":[0],"e":[100]},{"t":51}]},"r":{"k":180},"p":{"k":[-151.5,421,0]},"a":{"k":[768.5,421,0]},"s":{"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":{"i":[[1.571,12.855],[7.857,7.856],[0,0],[16.917,-16.917],[-16.918,-16.918],[0,0],[0,0],[-16.918,-16.917],[-16.917,16.918],[0,0]],"o":[[-0.559,-10.344],[0,0],[-16.918,-16.917],[-16.918,16.918],[0,0],[0,0],[-16.918,16.917],[16.917,16.918],[0,0],[9.813,-9.813]],"v":[[156.527,-3.861],[143.909,-32.24],[-79.662,-255.812],[-141.18,-255.812],[-141.18,-194.293],[53.247,0.134],[-140.913,194.294],[-140.913,255.812],[-79.395,255.812],[144.176,32.241]],"c":true}},"nm":"path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.83,0.45,0.08,1]},"o":{"k":100},"nm":"fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[340.484,420.945],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"convert"}],"nm":"group1","np":2,"mn":"ADBE Vector Group"}],"ip":0,"op":750,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":2,"ty":4,"nm":"“right”profile","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":0,"s":[0],"e":[100]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":29,"s":[100],"e":[0]},{"t":51}]},"r":{"k":180},"p":{"k":[292.5,421,0]},"a":{"k":[768.5,421,0]},"s":{"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":{"i":[[1.571,12.855],[7.857,7.856],[0,0],[16.917,-16.917],[-16.918,-16.918],[0,0],[0,0],[-16.918,-16.917],[-16.917,16.918],[0,0]],"o":[[-0.559,-10.344],[0,0],[-16.918,-16.917],[-16.918,16.918],[0,0],[0,0],[-16.918,16.917],[16.917,16.918],[0,0],[9.813,-9.813]],"v":[[156.527,-3.861],[143.909,-32.24],[-79.662,-255.812],[-141.18,-255.812],[-141.18,-194.293],[53.247,0.134],[-140.913,194.294],[-140.913,255.812],[-79.395,255.812],[144.176,32.241]],"c":true}},"nm":"path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.83,0.45,0.08,1]},"o":{"k":100},"nm":"fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[340.484,420.945],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"convert"}],"nm":"group1","np":2,"mn":"ADBE Vector Group"}],"ip":0,"op":750,"st":0,"bm":0,"sr":1},{"ddd":0,"ind":4,"ty":4,"nm":"“right”profile","ks":{"o":{"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"n":["0p833_0p833_0p167_0p167"],"t":0,"s":[100],"e":[0]},{"t":27}]},"r":{"k":-180},"p":{"k":[768.5,421,0]},"a":{"k":[768.5,421,0]},"s":{"k":[100,100,100]}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ks":{"k":{"i":[[1.571,12.855],[7.857,7.856],[0,0],[16.917,-16.917],[-16.918,-16.918],[0,0],[0,0],[-16.918,-16.917],[-16.917,16.918],[0,0]],"o":[[-0.559,-10.344],[0,0],[-16.918,-16.917],[-16.918,16.918],[0,0],[0,0],[-16.918,16.917],[16.917,16.918],[0,0],[9.813,-9.813]],"v":[[156.527,-3.861],[143.909,-32.24],[-79.662,-255.812],[-141.18,-255.812],[-141.18,-194.293],[53.247,0.134],[-140.913,194.294],[-140.913,255.812],[-79.395,255.812],[144.176,32.241]],"c":true}},"nm":"path 1","mn":"ADBE Vector Shape - Group"},{"ty":"fl","fillEnabled":true,"c":{"k":[0.83,0.45,0.08,1]},"o":{"k":100},"nm":"fill 1","mn":"ADBE Vector Graphic - Fill"},{"ty":"tr","p":{"k":[340.484,420.945],"ix":2},"a":{"k":[0,0],"ix":1},"s":{"k":[100,100],"ix":3},"r":{"k":0,"ix":6},"o":{"k":100,"ix":7},"sk":{"k":0,"ix":4},"sa":{"k":0,"ix":5},"nm":"convert"}],"nm":"group1","np":2,"mn":"ADBE Vector Group"}],"ip":0,"op":750,"st":0,"bm":0,"sr":1}],"v":"4.5.3","ddd":0,"ip":0,"op":51,"fr":25,"w":1537,"h":842}

return(<View style={{width:width,height:height-height/3, justifyContent:'center',}}>
                    <LottieView
                        style={{width: width/3, height: width/6,alignSelf:'center',}}
                        source={(this.state.index) ? require('../../image/lottie/batRight.json') : require('../../image/lottie/batLeft.json')}
                        imageAssetsFolder='../../image/lottie/'
                        autoPlay={true}
                        loop
                        resizeMode='cover'
                    />
                    <TouchableOpacity style={[styles.btnStyle, {backgroundColor: 'green', }]}
                                      onPress={ ()=>{ this.setState({ index: false, }) } } >
                        <Text style={styles.FTxt}>NEXT</Text>
                    </TouchableOpacity>
                </View>);

**Comment by emilioicai** [comment]
@s349856186 conditional requiring always brings issues (even with images) could you try something like this instead?

```
return(<View style={{width:width,height:height-height/3, justifyContent:'center',}}>
    {this.state.index && <LottieView
        style={{width: width/3, height: width/6,alignSelf:'center',}}
        source={require('../../image/lottie/Right.json')}
        imageAssetsFolder='../../image/lottie/'
        autoPlay={true}
        loop
        resizeMode='cover'
    />}
    {!this.state.index && <LottieView
        style={{width: width/3, height: width/6,alignSelf:'center',}}
        source={require('../../image/lottie/Left.json')}
        imageAssetsFolder='../../image/lottie/'
        autoPlay={true}
        loop
        resizeMode='cover'
    />}
    <TouchableOpacity style={[styles.btnStyle, {backgroundColor: 'green', }]}
                        onPress={ ()=>{ this.setState({ index: false, }) } } >
        <Text style={styles.FTxt}>NEXT</Text>
    </TouchableOpacity>
</View>);
```

**Comment by s349856186** [comment]
@emilioicai It's work for me, thanks
