### ISSUE TITLE
Animation works perfectly fine on web! But doesnt work in mobile preview mode.

### ISSUE THREAD

**Issue by Rahulroxguac** [react-native-community/lottie-react-native#349]
I exported a .json file from after effects and checked it on web and works perfectly fine. But it remains static and does not move on  mobile preview. someone please help. 
[Desktop.zip](https://github.com/react-community/lottie-react-native/files/2175743/Desktop.zip)

**Comment by emilioicai** [comment]
Hey, can you share some code showing how the animation is started up in your react native app?

**Comment by Rahulroxguac** [comment]
Can you please check whether the after effects file works in preview in lottie android or ios

**Comment by 1pocketaces1** [comment]
I have this same issue. I am moving my app from angular to RN, I have lottie animations that worked fine in angular but they are not playing in RN. They load to the first frame and then don't play. I have tried using both autoplay={true} and running this.animation.play() on componentDidMount()

**Comment by rodrigoelp** [comment]
Hey @Rahulroxguac, the zip file you uploaded is missing files (two illustrator files)...

Also, when I open the file I can see immediately 18 warnings:

![image](https://user-images.githubusercontent.com/301434/47251040-e2246480-d478-11e8-87aa-7ccb4028a99c.png)

Some of them are expressions (which are not supported by lottie and some of this will generate errors in react native).

If you want to use those animations, you got to specify keyframes

**Comment by duynd1** [comment]
In my case, my json file working well on web preview but it does not show on mobile preview, someone please help.
[likebutton.json.zip](https://github.com/react-community/lottie-react-native/files/2623865/likebutton.json.zip)

**Comment by rodrigoelp** [comment]
Hi @duynd1, on one hand I can see the embedded image as part of the json file and I don't think that is supported (reading the code [here](https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/Models/LOTAsset.m#L48) it points out as image name as opposed to just image).

So, starting from there, that might be giving you an issue.

**Comment by emilioicai** [comment]
closed due to inactivity

**Comment by sharmaabhay18** [comment]
Hey @rodrigoelp, I am facing an issue where in, the animation works fine in lottie view as well as on android although in iOS the last frames are lost.
Here is my json file.

[data2.json.zip](https://github.com/react-native-community/lottie-react-native/files/3260979/data2.json.zip)

**Comment by rodrigoelp** [comment]
@sharmaabhay18 the file is way too big for me to validate it. You might need to check the illustrator file first to identify the boundary of your animations.
