### ISSUE TITLE
Cannot read property Commands of undefined

### ISSUE THREAD

**Issue by safrankamate** [react-native-community/lottie-react-native#355]
Added Lottie to React Native project according to the [instructions on the website](http://airbnb.io/lottie/react-native/react-native.html#getting-started). App builds and launches fine, but the animation does not work.

On Android, it crashes with the error message **Cannot read property Commands of undefined** at `UIManager.LottieAnimationView.Commands[name]`:

```javascript
  runCommand(name, args = []) {
    return Platform.select({
      android: () =>
        UIManager.dispatchViewManagerCommand(
          this.getHandle(),
          UIManager.LottieAnimationView.Commands[name],
          args,
        ),
      ios: () => LottieViewManager[name](this.getHandle(), ...args),
    })();
  }
```

I debugged `UIManager` to the console inside `runCommand()` and it does not contain `LottieAnimationView` or any similarly named member.

On iOS, it does not crash but it does not display the animation either.

**Comment by safrankamate** [comment]
Addendum: for the sake of debugging, I tried replacing `_reactNative.UIManager.LottieAnimationView.Commands[name]` with `1` (which is supposed to be the value of the `PLAY` constant in `LottieAnimationView`); in this case, the app crashed with the error **Trying to send command to a non-existing view with tag 309**.

**Comment by lucasriondel** [comment]
same here. any update on this ?

**Comment by jkwangbest** [comment]
+1

**Comment by devpascoe** [comment]
For me i forgot to add new LottiePackage() to the react instance manager for android when adding packages. http://airbnb.io/lottie/react-native/react-native.html#android

**Comment by Monte47** [comment]
^^ This worked for me. For some reason `react-native link...` didn't do this step.

**Comment by emilioicai** [comment]
closed due to inactivity

**Comment by kiranjd** [comment]
Manually link the package

**Comment by ishiestar** [comment]
I am getting this error on android too, and my lib is properly linked. I cannot figure out why this is happening. It runs fine on iOS and shows the animation as expected.

This is the error:

    TypeError: Cannot read property 'Commands' of null
    This error is located at:
    in AnimatedComponent (at LottieView.js:177)

**Comment by myrickchowRedso** [comment]
I can solve it by adding `new LottiePackage()` at the `getPackages` callback in `MainApplication.java` as stated above by devpascoe. 

My Lottie version is `3.4.0` and react-native version is `0.62.2`.

Please run the whole project again by `react-native run-android` instead of just reloading the project by Command+R. Since native code is changed, hot reload does not refresh the native codes and the issue would still be there.
