### ISSUE TITLE
Problem with FlatList in ReactNative

### ISSUE THREAD

**Issue by behiunforgiven** [react-native-community/lottie-react-native#356]
I use lottie in a FlatList and only the last item shows the animation. (Lottie works fine in other parts of project)
How can I solve this problem?

**Comment by emilioicai** [comment]
are you using the declarative or the imperative API? can you share some code?

**Comment by behiunforgiven** [comment]
Thank you.
I removed it from my code, but it is a simple FlatList and in renderItem I use 
```
      <LottieView source={require('../path/to/animation.json')} progress={this.state.progress} />
```

as the same in documents
but only the last item of list shows the animation.

**Comment by emilioicai** [comment]
closed due to inactivity
