### ISSUE TITLE
[Apple Tv] - Lottie react native showing error in tvOS(apple tv)

### ISSUE THREAD

**Issue by oormilavarma** [react-native-community/lottie-react-native#357]
I was trying to run my react native application which contains lottie-react-native in tvOS(i.e. on apple tv) and it seems that lottie doesn't support tvOS. It's working perfectly fine in mobile(both ios and android) and android TV also.

Is there anyway I could use it on tvOS as well?

**Comment by emilioicai** [comment]
closed due to inactivity
