### ISSUE TITLE
Animation pauses before looping

### ISSUE THREAD

**Issue by 1pocketaces1** [react-native-community/lottie-react-native#377]
### Description

When animation loops it pauses before looping.

### Steps to Reproduce

Here is my class for autoplay lottie animations:
export default class Autoplay extends Component {

 ```
 constructor(props) {
    super(props);
    this.state = {
      speed: this.props.speed
    }
  }

  // componentDidMount() {
  //   this.animation.play();
  // }

  render() {

    return(
      <LottieView
        ref={
          animation => {
            this.animation = animation;
          }
        }
        style={fill}
        source={anims[this.props.anim]}
        loop={true}
        autoPlay={true}
      />
    )
  }
```

**Expected behavior:**I expect when looping there should be a continuous loop with no pause

**Actual behavior:** Animation pauses before looping

### Versions

react native 0.56.0
lottie react native 2.5.6

**Comment by rodrigoelp** [comment]
Hi @1pocketaces1, I have not noticed this behaviour, could you attach the animation you are trying to use? I can imagine that setting up this example shouldn't be too much a problem.

**Comment by emilioicai** [comment]
closed due to inactivity
