### ISSUE TITLE
Animation not working on iOS

### ISSUE THREAD

**Issue by maggialejandro** [react-native-community/lottie-react-native#379]
### Description
PinJump animation does not work on iOS, it works fine on Android though

### Steps to Reproduce

```javascript
// @flow
import React from 'react';
import LottieView from 'lottie-react-native';

// eslint-disable-next-line
export default class AnimatedLoading extends React.Component<{}> {
  render(): React.Element {
    return (
      <LottieView
        style={{
          width: 100,
          height: 100,
        }}
        source={require('./PinJump.json')}
        autoPlay
        loop
        enableMergePathsAndroidForKitKatAndAbove
      />
    );
  }
}
```

<img width="719" alt="captura de pantalla 2018-09-04 a la s 14 50 51" src="https://user-images.githubusercontent.com/3394748/45048335-03103200-b052-11e8-8315-ae18924a300d.png">
<img width="257" alt="captura de pantalla 2018-09-04 a la s 14 50 33" src="https://user-images.githubusercontent.com/3394748/45048336-03103200-b052-11e8-9731-cfeb9560d392.png">
<img width="514" alt="captura de pantalla 2018-09-04 a la s 14 50 25" src="https://user-images.githubusercontent.com/3394748/45048337-03103200-b052-11e8-9a10-2c1fada78fce.png">
<img width="508" alt="captura de pantalla 2018-09-04 a la s 14 50 18" src="https://user-images.githubusercontent.com/3394748/45048338-03a8c880-b052-11e8-971c-35c8a1a64a39.png">

Lottie.framework is missing on npm folder.

<img width="555" alt="captura de pantalla 2018-09-04 a la s 14 52 56" src="https://user-images.githubusercontent.com/3394748/45048416-3e126580-b052-11e8-94d2-5b184a42ad5c.png">

### Versions
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  react: ^16.4.2 => 16.4.2
  react-native: ^0.55.4 => 0.55.4

  lottie-react-native: 2.5.8

**Comment by HashDot** [comment]
Same here. iOS doesn't work but android works.

lottie-react-native: 2.5.8
react-native: 0.56

{ app: '0.1.0',
  npm: '5.6.0',
  ares: '1.14.0',
  cldr: '33.0',
  http_parser: '2.8.0',
  icu: '61.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.29.0',
  node: '10.0.0',
  openssl: '1.1.0h',
  tz: '2018c',
  unicode: '10.0',
  uv: '1.20.2',
  v8: '6.6.346.24-node.5',
  zlib: '1.2.11' }

**Comment by njho** [comment]
Same

**Comment by wmonecke** [comment]
+1

Same here. I dont get any build errors or anything and have tried other solutions people have been proposing, like removing `Lottie.framework` from `Link Binary with Libraries`. I have not tried Android yet.

**Comment by jessalbarian** [comment]
I had the same issue and was able to get it working by running
`pod install`
in my ios folder where the Podfile is.

**Comment by rodrigoelp** [comment]
Hi guys, trying to be helpful here. I do not have issues with lottie for this version of xcode, maybe I can be of assistance?

Could you please provide the set of steps you did to reproduce it (from `react-native init X`)?

**Comment by Dihan101** [comment]
Finally! after a lot of reading solutions. I just fixed this by updating my react-native and xcode to latest version and reinstall lottie-react-native from start.

**Comment by vahidreza** [comment]
@jessalbarian there is no pod file inside my ios project. I have install cocoapods and then react-native-pod and run the pod install inside my ios folder and it said 0 new pods with 0 dependency have been installed. I did npm run ios but again my animation not playing is ios but works in android.
this is an odd issue.
im using XCode 10 and react-native: 0.55.4

**Comment by jessalbarian** [comment]
@vahidreza I added these to my Podfile:

pod 'lottie-ios', :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

Then run `pod install`

**Comment by Dihan101** [comment]
@ofri84 I'm sorry for the late response. 
For the assurance fix.

1. Remove first your `node_modules` folder by `rm -rf node_modules` and `npm install` again.
2. (Important) Please make sure you followed clearly the installation for IOS and Android. Please don't install lottie-ios if you thought that installation command you to link even it's not yet installed.
3. Please don't ignore this phrase after the linking 

> After this, open the Xcode project configuration and add the Lottie.framework as Embedded Binaries.

Open your `yourapp.xcodeproj` and do this:
![image](https://user-images.githubusercontent.com/14257120/48856509-83dcff80-edf1-11e8-9c44-e628fa7f0777.png)

4. Uninstall your app from simulator.
5. run `react-native run-ios`, wait until it build. then terminate by `ctrl+c`.
6. run `react-native start --reset-cache`.
7. Restart your simulator by hitting `command+R`.

And poof! It should work smoothly.
I hope this will help you.

**Comment by lorenc-tomasz** [comment]
I have added all dependences manually without Pods and it works.

**Comment by kaushal9678** [comment]
I was facing same issue, I did following things and it worked fine on both iOS and Android

First I install pod file in iOS folder by using pod init

Then install npm i --save lottie-react-native

After installing lottie-react-native run link command
* react-native link lottie-ios
*react-native link lottie-react-native

Go to Xcode and in libraries folder add lottie-ios and lottie-react-native xcode project like attached screenshot from node_modules

Then add Lottie.framework from Lottie products to Embedded Binaries

add libLottieReactNative.a and libLottie.a to Linked frameworks and libraries. That .a file you can find in Libraries product folder. See enclosed screenshot 2
1. 
<img width="271" alt="screenshot 2019-01-06 at 11 32 46 am" src="https://user-images.githubusercontent.com/4991337/50733087-9e561700-11ac-11e9-8ade-e9b1bbbf8253.png">
2. <img width="660" alt="screenshot 2019-01-06 at 12 05 32 pm" src="https://user-images.githubusercontent.com/4991337/50733089-a1510780-11ac-11e9-8ef6-5b489d8b55b6.png">
3. Final Outcome 
<img width="372" alt="screenshot 2019-01-06 at 12 12 02 pm" src="https://user-images.githubusercontent.com/4991337/50733091-ac0b9c80-11ac-11e9-9d12-0cdc2f56f568.png">

**Comment by liangzhm** [comment]
i have the same issuse,lottie doesn't work on ios,but work well on android. react version is 16.0.0,react-native version is 0.45.1,who can help me

**Comment by kaushal9678** [comment]
@liangzhm, Did you check with steps as I mentioned above? Because it didn't find your Lottie framework and **.a libLottie. and LibLottieReactNative.a** files add these manually from node_modules.

**Comment by calz10** [comment]
@Dihan101  thnks! your solution works great! removing the node_modules and deintegrating pod file and redo the process above will make it work! I've downgraded the version to @2.3.2 works fine as a test and again turn it to the latest version

**Comment by calz10** [comment]
![screen shot 2019-03-01 at 2 23 44 pm](https://user-images.githubusercontent.com/9754952/53620393-bc307d00-3c2d-11e9-8b65-f5689aa80a3e.png)

**Comment by ollydixon** [comment]
Where can we download Lottie.framework?

**Comment by BaderSerhan** [comment]
@ollydixon same! I don't seem to find Lottie.framework

**Comment by HashDot** [comment]
@ollydixon @BaderSerhan 

Follow the instructions: https://github.com/react-native-community/lottie-react-native#installing-react-native--058x

After this you can add the Lottie.framework in Xcode. Click on the plus icon and search for "Lottie".

Or update to RN 0.60 and use the auto link feature.

**Comment by Dihan101** [comment]
> @Dihan101 thnks! your solution works great! removing the node_modules and deintegrating pod removing the lottie and installing other pod files. and redoing the process above will make it work! I've downgraded the version to @2.3.2 works fine as a test and again turn it to the latest version. No need to pod install when you link packages manually, furthermore, "liblottie.a" doesnt need to be in the binary library just the framework :)
> ![screen shot 2019-03-01 at 1 55 59 pm](https://user-images.githubusercontent.com/9754952/53619296-cc465d80-3c29-11e9-89bd-34bfcba4e548.png)

Thank you! I appreciate your feedback @calz10

**Comment by shaquill-oatmeal** [comment]
Just want to mention that removing the node_modules and running npm i again made it work
