### ISSUE TITLE
cacheStrategy causing error

### ISSUE THREAD

**Issue by hodatorabi** [react-native-community/lottie-react-native#381]
### Description
The below code will run without any errors when I don't pass the cacheStrategy props but with cacheStrategy it throws an error similar to the screenshot that I've included.

![screenshot from 2018-09-11 12-10-15](https://user-images.githubusercontent.com/18525727/45345571-fb094280-b5bb-11e8-945b-478346cf8cc4.png)

```
<AnimatedLottieView
					source={SPLASH_ANIMATION}
					style={style.launchImage}
					resizeMode='cover'
					progress={this.state.progress}
					cacheStrategy={'strong'}
				/>

```
I've tried passing 'weak' and 'none' too but it still crashes.

**Comment by stokesbga** [comment]
what? is that part of the requirement to use cachestrategy?

**Comment by emilioicai** [comment]
no, the `source` should be a required file. Something like this:

```
<AnimatedLottieView
	source={require('../animations/animation1.json')}
	style={style.launchImage}
	resizeMode='cover'
	progress={this.state.progress}
	cacheStrategy={'strong'}
/>
```

**Comment by hodatorabi** [comment]
@emilioicai no SPLASH_ANIMATION is sth like this: 
`export const SPLASH_ANIMATION = require('src/assets/motions/splash.json')`
