### ISSUE TITLE
[Android] [deprecation] loop(boolean) in LottieAnimationView has been deprecated

### ISSUE THREAD

**Issue by kirankalyan5** [react-native-community/lottie-react-native#392]
I see this warning when I run the android build.

```
/LottieAnimationViewPropertyManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

when I run with `-Xlint:deprecation`

`lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.java:118:`

```
warning: [deprecation] loop(boolean) in LottieAnimationView has been deprecated
      view.loop(loop);
          ^
1 warning
```

**Comment by rodrigoelp** [comment]
Uh, interesting... it seems the call needs to be updated to `view.setRepeatCount(LottieDrawable.INFINITE);` (which is what loop does)

**Comment by rodrigoelp** [comment]
Ah, unfortunate... and annoying.

[Lottie-android](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L609) has the definition for `setRepeatCount`

The [iOS](https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/PublicHeaders/LOTAnimationView.h) counterpart doesn't have it publicly... although the actual [implementation](https://github.com/airbnb/lottie-ios/blob/master/lottie-ios/Classes/Private/LOTAnimationView.m#L400) uses a core animation that allows you to set it (or expose it) if required.

**Comment by kirankalyan5** [comment]
@rodrigoelp Thanks for looking it through!
Any possible solutions to avoid these error?

If I get an idea I would be happy to raise a PR.

**Comment by rodrigoelp** [comment]
Yes @kirankalyan5, I mentioned it above... one way is to reimplement the way `loop={true}` works to call internally `view.setRepeatCount(...)` as opposed to the `view.loop()` method.

Although, technically this is not an error ;)

I've created a pull request with the change, though my testing was pretty quick, so I am going to suggest to @emilioicai to test it a bit more.
