### ISSUE TITLE
Was unable to install Lottie until I removed our Podfile (Asking how I can help improve the project)

### ISSUE THREAD

**Issue by Rnorback** [react-native-community/lottie-react-native#407]
### Description

I'm currently working on two react-native projects. When I installed Lottie in the smaller project that doesn't have any Pods installed, it worked like a charm - no problems. When I tried to install Lottie in the larger project that has Pods installed there was no end to the trouble.

### Steps to Reproduce

1. Create react-native project and have at least one pod installed (you simply need a Podfile).
2. Follow the steps to install Lottie (run yarn add, react-native link).You end up with a modified Podfile with Lottie pods in it linked back to the node-module files.
3. Run `Pod install` in your iOS folder on your react native project

**Expected behavior:** [What you expected to happen]
Will install Lottie including the .framework and .a files needed to use the package in your project.

**Actual behavior:** [What actually happened]
You'll run into aerror after error while trying to get the pods to play nice with react-native. First error was two versions of react-native that were colliding with each other. (I had to completely change our implementation of RN to get things to compile, but then Lottie still didn't work).

### Solution
After spending 2 hours and modifying 3M lines of code, lol, I figured out I could do the following:

1. Delete the Podfile
2. Run `yarn add lottie-react-native`, react-native link etc.
3. Add lottie.framework to embedded binaries
4. Add back the Podfile

Then everything worked perfectly.

### Proposal
I'd love to add this to the README or make a PR to fix `react-native link` when a Podfile is present in a react-native project. I'm not sure how to do the latter, if you know you could point me in the right direction and I can work on and make a PR.

Really just want to know what'll be most helpful before a sink some time into this. Cheers!

### Versions

RN 0.56
node: '10.9.0'
Lottie: v2.5.10

**Comment by emilioicai** [comment]
Hi @Rnorback , thanks a lot for your contribution!

This has been indeed something I tried to fix a couple of times but didn't succeed. I guess the problem is the way the podspec is defined but I'm a pure RN developer and I'm lacking knowledge in how pods are internally built so it would be great if you could help on it. A PR would be greatly appreciated. As a reference, I would recommend this article: http://artsy.github.io/blog/2018/04/17/making-a-components-pod/ 

Thanks again, let me know if you need any help on this.

**Comment by HexNeck** [comment]
That woud be amazing as I did spend really a lot of time on this as well and I think I broke the project I was working on.

**Comment by emilioicai** [comment]
@Rnorback Yeah, I think we need to add some documentation about how to build properly when pods are present but I'm not sure if deleting the Podfile is a good idea. I will investigate a bit if we can prevent the link command from modifying the Podfile

**Comment by ValterSantosMatos** [comment]
I could build it after manually adding the projects to the Library folder just like [here](https://github.com/react-native-community/lottie-react-native/issues/242#issuecomment-364887229)

**Comment by zinoviev** [comment]
This issue is still relevant - lottie-react-native can't be installed with pod incorporated proejct, unless you know about @Rnorback hack
