### ISSUE TITLE
LottieAnimationView but name was already registered by class ExAnimationViewManager

### ISSUE THREAD

**Issue by almsx** [react-native-community/lottie-react-native#409]
### Description

I can not use Lottie in a reactive native application made using Expo to which I have done a detach to add Push Notifications, Background Timer, etc.

[Description of the bug]
When I have managed to implement a lottie-ios or lottie-react-native project, a window appears in red that is attached to the ticket issue and does not allow me to go through this window.

### Steps to Reproduce

1. Make detach. exp detach
2. Add lottie. 
$ npm i --save lottie-react-native
$ react-native link lottie-ios
$ react-native link lottie-react-native
3.- Ingress en iOS folder.
4.- Make  a pod install
$ pod install

3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
![simulator screen shot - iphone xr - 2018-11-15 at 00 39 25](https://user-images.githubusercontent.com/361558/48541620-a49dd600-e882-11e8-93af-48c87ee2d3f3.png)

### Versions

You can get this information from executing `npm version`.

{ npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.13.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.36',
  zlib: '1.2.11' }

**Comment by MonicaGandhi24** [comment]
I am still facing this issue, @almsx did you figure out on how to resolve it?

**Comment by zanechua** [comment]
@MonicaGandhi24 

If you're using expo, expo itself has lottie-react-native. You should remove any lottie packages that have been added by `react-native link`, e.g. `lottie-ios`. This solved the issue for me. There's no need to link those packages if i'm not mistaken.
