### ISSUE TITLE
[ANDROID] Progress not working with autoplay/play

### ISSUE THREAD

**Issue by robinclaes** [react-native-community/lottie-react-native#410]
### Description

When setting progress at for example .5, playing the animation starts from 0 on Android.
This works fine on iOS.

### Steps to Reproduce

1.  Set progress on a LottieView
2. Play the animation (ref.play() or autoplay)

**Expected behavior:**
The animation starts playing from the set progress (.5)

**Actual behavior:** 
The animation starts playing from 0

### Versions
Lottie-react-native: 2.5.10
React native: 0.57.0

**Comment by nasreekar** [comment]
Is this issue resolved?

**Comment by TechySharnav** [comment]
I am facing the same issue!

**Comment by HelloJack0** [comment]
@emilioicai This issue how to resolved? Can you help me? Thanks

**Comment by HelloJack0** [comment]
@emilioicai This issue how to resolved? Can you help me? Thanks

**Comment by TechySharnav** [comment]
> @emilioicai This issue how to resolved? Can you help me? Thanks

Try Setting loop to false.
If that doesn't work, try below code (its technical tho)

Add 'progress' in the state:-
`this.state = {progress: 0}`

You can replace 0 with starting progress value you want. Then add below in ComponentDidMount().

`var interval = setInterval(()=>{this.setState({progress:this.state.progress + 1/Totalframes})}, 1/FPS)`

Now, replace Totalframes with with total number of frames in your animation and FPS with frame rate of your animation.

You may also want to add following in setInterval to clear the interval when progress reaches end. 

`if(this.state.progress >= 1){clearInterval(interval)}`


Now, set autoplay and loop props of LottieView to false, and progress to this.state.progress

This might not be the best way to achieve this but I was able to find this workaround.

Hope this helps!!
