### ISSUE TITLE
[ANDROID] adding text to an animation causes app on android to crash

### ISSUE THREAD

**Issue by kreativ-software** [react-native-community/lottie-react-native#411]
### Description

Adding text to an animation (in AE) causes the app on android to crash instantly, on ios its just not displaying it(as expected)
The animation also does not load in the example lottie app download-able from the playstore. (error: "There was an error loading the composition")
Glyphs on or off does not make a difference either

### Steps to Reproduce

1. Make a simple AE animation without text and test it. (works)
2. Add text to the simple animation and test it again. (doesn't work)

**Expected behavior:** Text renders on android (as listed [here](http://airbnb.io/lottie/supported-features.html)) and not on ios.

**Actual behavior:** App crashes on android (emulator as well as real device) and on ios it doesn't display text.

### Versions

lottie-react-native: 2.5.10
node.js: 11.2.0
react-native: 0.57.5
android: 8.0.0 - 8.1
os: windows 10
AE: 14.2.0.198
bodymovin AE-plugin: 5.3.4

**Comment by emilioicai** [comment]
Is your text using a non supported after effect feature maybe?

**Comment by emilioicai** [comment]
this is the list of supported features http://airbnb.io/lottie/supported-features.html

**Comment by kreativ-software** [comment]
I just checked to make sure, but its just a normal text layer, it also works fine if i use it in lottie-web, just not on android. 
I added a screenshot of the layer in after effects.
![image](https://user-images.githubusercontent.com/3669669/49016281-e2a1d080-f185-11e8-8179-6c059e9706e5.png)

**Comment by emilioicai** [comment]
yeah, I'm afraid Anchor point grouping is not supported in android or iOS. Could you try setting it to none?

**Comment by kreativ-software** [comment]
![image](https://user-images.githubusercontent.com/3669669/49017340-ea16a900-f188-11e8-8ff9-9b88eefd4f3a.png)
There is no "none" options and none of the other options seem to "fix" it

**Comment by emilioicai** [comment]
oh, true, I will check with someone who knows more about AE
