### ISSUE TITLE
Different animation scaling on android and ios

### ISSUE THREAD

**Issue by kkrauthaeuser** [react-native-community/lottie-react-native#428]
### Description

Just started using Lottie, but the animations aren't styled consistently on android and iOS.

### Steps to Reproduce

I'm using this animation: [link](https://www.lottiefiles.com/72-favourite-app-icon)

This is my Component Tree:

```
<View style={{
  position: 'absolute',
  width: '100%',
  height: '100%',
  alignItems: 'center',
  justifyContent: 'center',
}}
>
  <LottieView
    autoPlay
    ref={(animation: any) => {
      this.animation = animation;
    }}
    style={{
      position: 'absolute',
      height: '100%',
      width: '100%',
    }}
    resizeMode="cover"
    loop
    source={require('../../../animations/favourite_app_icon')}
  />
</View>
```

In this config, the android animation is about twice. the size of the iOS version. If I remove `resizeMode="cover"`, the android version is way smaller than the iOS version.

It might be important to note that the size of the iOS-version isn't affected by the resizeMode and that the other resizeModes result in similar results.

Thanks in advance.

**Comment by aHandToHelp** [comment]
Can we add this to the props docs please?

**Comment by erayaras** [comment]
Thanks @kkrauthaeuser.

For Android, I use following code and It works.

`              <View style={{
                position: 'absolute',
                width: '100%',
                height: '100%',
                alignItems: 'center',
                justifyContent: 'center',
              }}
              >
                <LottieView
                  source={require('../../../App/Assets/Lottie/foreground/cute-little-panda-sleeping.json')}
                  style={{
                    position: 'absolute',
                    height: height/1.5,      //different than yours
                    width: '100%',
                  }}
                  resizeMode="cover"
                  autoPlay
                  loop
                  speed={1}
                />
               </View>`

**Comment by erheron** [comment]
@emilioicai let me write here instead of opening another issue.
I can't find any mention of `resizeMode` prop in the [API Documentation](https://github.com/lottie-react-native/lottie-react-native/blob/master/docs/api.md). Meanwhile, seems like the prop exists and works. Could we add this to docs? 🙏🏻
