### ISSUE TITLE
Android Empty File name

### ISSUE THREAD

**Issue by Lilystar8888** [react-native-community/lottie-react-native#433]
Error : Empty File name
![1547177857482](https://user-images.githubusercontent.com/34956684/51082905-17281680-174b-11e9-81c6-1c06736e8b85.jpg)

**Android keeps reporting error as Empty File name (IOS is okay)**

<LottieView
     source={this.state.Gifts[0][0].g6}
     **imageAssetsFolder={'lottie/'}**
/>
source is dynamically from imported Array which has been pushed into this.state.Gifts.
The array pushed to this.state.Gifts is like: [ 
{"g6": require('../../../../design/common/lottie/animation01.json') },
{"g6": require('../../../../design/common/lottie/animation02.json') }
];

**Not sure the error msg 'empty file name' means 'can't find images' or not...**

Images has been copied to **[PROJECT FOLDER]/android/app/src/main/assets/lottie/**.
image path set in json asset as "u": "images/".
Tried to do a folder per animation under android/app/src/main/assets/lottie/ but not solved.
Tried to copy json files to android assets folder, and change source path to that, but still not solved.

"lottie-react-native": "^2.5.11", (not solved even downgrade to 2.5.5)
"react": "16.3.1",
"react-native": "0.55.3"

**Comment by SandeshVakale** [comment]
I had the same issue. I removed `cacheStrategy` and it started working.

**Comment by pouya92** [comment]
I have same issue, is there any ways instead of removing cacheStrategy ?

**Comment by Lilystar8888** [comment]
json-files  in /android/app/src/main/assets/lottie/
relevant images in /android/app/src/main/assets/lottie/imagesFolder

**Comment by Lilystar8888** [comment]
> I have same issue, is there any ways instead of removing cacheStrategy ?

imagesFolder

**Comment by Lilystar8888** [comment]
> I have same issue, is there any ways instead of removing cacheStrategy ?

All json-files  in /android/app/src/main/assets/lottie/
All relevant images in /android/app/src/main/assets/lottie/imagesFolder
