### ISSUE TITLE
Build Failed lottie ^2.5.11

### ISSUE THREAD

**Issue by unsolvedru** [react-native-community/lottie-react-native#434]
\> Configure project :lottie-react-native
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':lottie-react-native'.
\> java.lang.NullPointerException (no error message)

====================================================
package.json
"lottie-react-native": "^2.5.11",
"react": "16.6.3",
"react-native": "0.57.8"

====================================================
steps

1. npm i -s lottie-react-native
2. react-native link lottie-react-native
3. react-native run-android

====================================================
configs:
> android/gradle/wrapper/gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-5.0-all.zip

**Comment by nelsonchen5** [comment]
+1

**Comment by maggialejandro** [comment]
Adding this to app/build.gradle fixed the build
```gradle
compileOptions {
  sourceCompatibility 1.8
  targetCompatibility 1.8
}
```

**Comment by nelsonchen5** [comment]
@maggialejandro this does not fix the build for me

**Comment by MateusAndrade** [comment]
@maggialejandro i tried this, but it keeps trhwoing a Null POinter. :(

**Comment by clh97** [comment]
+1

**Comment by evanjmg** [comment]
Same here but I'm getting this...
```
/Users/evangillogley/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/373c20edc9370a1ed4115662efb25fde/res/values-v24/values-v24.xml:3:5-157: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/Users/evangillogley/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/373c20edc9370a1ed4115662efb25fde/res/values-v24/values-v24.xml:4:5-135: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/Users/evangillogley/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/373c20edc9370a1ed4115662efb25fde/res/values-v26/values-v26.xml:13:5-16:13: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
  
```

**Comment by MateusAndrade** [comment]
@evanjmg i have this problem a time ago, i solved this by using a specific version of the project. i will find how i fixed this and place the fix here. :)

**Comment by MateusAndrade** [comment]
@evanjmg  i have this problem a time ago, i solved this by using a specific version of the project

**Comment by Aung-Myint-Thein** [comment]
Which version you are using successfully? @MateusAndrade

**Comment by clh97** [comment]
currently working here with:
"lottie-react-native": "^2.5.11",
"react": "16.6.1",
"react-native": "0.57.7",
@Aung-Myint-Thein

**Comment by Aung-Myint-Thein** [comment]
Thanks for quick reply but when i build the android, I get 

`Could not find method compileOptions() for arguments [xxxx] on project ':app' of type org.gradle.api.Project`

It is working fine on iOS thou. I am also using:

"lottie-react-native": "^2.5.11",    
"react": "^16.6.1",    
"react-native": "^0.57.5",

**Comment by clh97** [comment]
Are you using 'android/app/build.gradle' file? Like that:
android {
...
compileOptions {
     sourceCompatibility 1.8
     targetCompatibility 1.8
}
...
}

**Comment by Aung-Myint-Thein** [comment]
Nice! Thanks. Now it is building properly.

**Comment by derek-diaz** [comment]
I was having the same issue and adding the compileOptions and doing a gradle clean fixed the issue for me.

``cd android``
``gradlew clean``
``cd ..``
``react-native run-android``

**Comment by emilioicai** [comment]
closed due to inactivity

**Comment by FoolCoder** [comment]
@maggialejandro  i changed my build file but still getting my build failed
