### ISSUE TITLE
new warning while upgrading to RN 0.58

### ISSUE THREAD

**Issue by OrLevy23** [react-native-community/lottie-react-native#437]
after upgrading to react native 0.58 (from 0.57) i've started to see a this warning:
Accessing view manager configs directly off UIManager via UIManager['LottieAnimationView'] is no longer supported. Use UIManager.getViewManagerConfig('LottieAnimationView') instead

**Comment by fantasy525** [comment]
same warning+1

**Comment by fantasy525** [comment]
![image](https://user-images.githubusercontent.com/22516157/51899023-1ea71b00-23ed-11e9-81bf-7e8fff2d7c94.png)

**Comment by emilioicai** [comment]
@fantasy525 can you confirm this only happens on android?

**Comment by mnsrv** [comment]
@emilioicai This happens on iOS too
![image](https://user-images.githubusercontent.com/8746547/52048658-ff2f0000-255c-11e9-9ddc-267738642c9d.png)

**Comment by michellmorso** [comment]
I can confirm that this is happening on IOS as well

**Comment by flisboac** [comment]
I suspect this is an upstream bug, related to how [`react-native-safe-module` uses UIManager](https://github.com/lelandrichardson/react-native-safe-module/blob/v1.2.0/src/NativeSafeComponent.js).

**Comment by LRNZ09** [comment]
I can confirm it happens both on Android and iOS.

**Comment by tokinonagare** [comment]
Is there any other way to resolve this problem?

**Comment by ananyacleetus** [comment]
Is there a way to fix this in react-native-safe-module?

**Comment by Sbphillips19** [comment]
Is there a fix for this yet?

**Comment by emilioicai** [comment]
@Sbphillips19 @ananyacleetus @tokinonagare @fantasy525 @OrLevy23 

It's indeed an issue with `react-native-safe-module` and the way we access the view manager module. I created a branch (`fix-warning` https://github.com/react-native-community/lottie-react-native/tree/fix-warning), can any of you guys try to reproduce using that branch in `lottie-react-native`? If that's still an issue I'm afraid we will need to use a replacement for `react-native-safe-module`

**Comment by flisboac** [comment]
@emilioicai Seems like [there's a PR open for this issue](https://github.com/lelandrichardson/react-native-safe-module/pull/6), but the project looks abandoned. Perhaps users could use something like [patch-package](https://www.npmjs.com/package/patch-package) in the meantime, at least until the author accepts the PR or lottie-react-native chooses a substitute (or forgoes the use of any safe module intermediary altogether, if possible).

**Comment by emilioicai** [comment]
@flisboac did you have any success with `patch-package`? I was thinking of stripping `react-native-safe-module` out of the project if nothing else fixes this warning. In case you manage to find a fix, can I ask for a PR? :)

**Comment by flisboac** [comment]
@emilioicai Sorry for the late reply.

In all honesty, I'm not a user of `lottie-react-native`, but regardless, I'll try to help as much as I can. I'll investigate this more thoroughly on the weekend, but here goes some questions:

1. Do you think it's feasible to remove `react-native-safe-module`? I just glanced at the code once or twice to solve a problem of one of my users, so I'm not entirely sure of `react-native-safe-module`'s relevance to `lottie-react-native` as a whole.
1. Do we depend on `react-native-safe-module`'s mocking mechanism in any way, or can we just use `UIManager` directly?

**Comment by wyzzy** [comment]
This is also confirmed as an issue on RN 0.59 on iOS

**Comment by sps100** [comment]
This is also confirmas an issue on RN 0.59.9 on Android

**Comment by sajaddp** [comment]
This also confirms an issue on RN 0.60.3 on Android

**Comment by ganoch** [comment]
this issue is still present in 3.0.2 for some reason

**Comment by ooyo-tech** [comment]
This also confirms an issue on RN 0.59.10 on Android

**Comment by ganoch** [comment]
@emilioicai why not fork react-native-safe-module and apply the patch and move on?

**Comment by emilioicai** [comment]
@ganoch yes, I think this is now the way to go. I will fork it and apply the patch for it
