### ISSUE TITLE
Trim Paths Problem

### ISSUE THREAD

**Issue by binsprout05** [react-native-community/lottie-react-native#439]
### Description

Hi, 

I've been using trim paths to animate the tears for an animation im working on. On after effects preview and lottie preview (http://lottiefiles.com/share/9Wjm2c) the animation plays correctly.

However when it is imported to React Native the animation turns out like this
https://vimeo.com/314487401.

It looks like a merge path error but i have deleted merge paths from my animation and the error still remains.

Attached is the AEP file for reference
(In the AEP, I deleted merge paths for the left stream of tears and kept it for the right stream of tears just for comparison sake)

Thank you so much!

[CPDLoadingFailure.aep.zip](https://github.com/react-native-community/lottie-react-native/files/2817408/CPDLoadingFailure.aep.zip)

**Comment by emilioicai** [comment]
Hi @binsprout05  trim paths are indeed supported but Merge paths aren't. Can you check if you are using any non supported feature from this list?: https://airbnb.io/lottie/supported-features.html

**Comment by binsprout05** [comment]
Hi Emilio,

Thank you for the quick reply.

I checked the list but unfortunately, I still cant find the problem. The animation isnt complicated just some movement, scaling and opacity and then trim paths. 

Thanks!

**Comment by binsprout05** [comment]
https://imgur.com/gallery/0ca6oCO

This is how it looks with merge paths deleted.
