### ISSUE TITLE
Android 5.x Masks problem

### ISSUE THREAD

**Issue by manuhook** [react-native-community/lottie-react-native#441]
Masks are not working anymore on Android 5.x. (and maybe 4)
In fact they are working but all the layers under the mask are not displayed.

The problem is not present on lottie-react-native 2.2.7
It's present on lottie-react-native 2.5.11 (I didn't test the versions between).

There is no problem on Android 6.x & >

**Comment by emilioicai** [comment]
do they work on lottie-android?

**Comment by manuhook** [comment]
I haven't tried, however I haven't seen any similar issue on this matter on lottie-android
