### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Nitaaq** [react-native-community/lottie-react-native#442]
Hello, 
I'm trying to build my project (Android) after linking lottie-react-native, 
Seems that my buildtools version doesnt satisfy version constraints. 
I'm getting alot of these errors in console.

* What went wrong:
Could not resolve all files for configuration ':lottie-react-native:debugCompileClasspath'.
> Could not resolve com.android.support:appcompat-v7:27.1.1.
  Required by:
      project :lottie-react-native
   > Cannot find a version of 'com.android.support:appcompat-v7' that satisfies the version constraints:
        Dependency path 'porjectOne:lottie-react-native:unspecified' --> 'com.facebook.react:react-native:0.58.3' --> 'com.android.support:appcompat-v7:28.0.0'
        Dependency path 'porjectOne:lottie-react-native:unspecified' --> 'com.airbnb.android:lottie:2.5.6' --> 'com.android.support:appcompat-v7:27.1.1'
        Constraint path 'porjectOne:lottie-react-native:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1
        Constraint path 'porjectOne:lottie-react-native:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1
        Constraint path 'porjectOne:lottie-react-native:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1
        Constraint path 'porjectOne:lottie-react-native:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1
        Constraint path 'porjectOne:lottie-react-native:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1

my buildscript ext is : 
{
        buildToolsVersion = "28.0.2"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }

any workaround this please ?

**Comment by rmilejcz** [comment]
In `node_modules/lottie-react-native/src/android/build.gradle` you need to change the `dependencies` to:

```java
dependencies {
  compileOnly "com.facebook.react:react-native:+"
  implementation "com.airbnb.android:lottie:2.5.6"
  implementation "com.android.support:appcompat-v7:28.0.0" // <- add this line
}
```

I'm not sure *why* you need to do that, but that fixed it for me

**Comment by rgoldiez** [comment]
This will also fix it... add to your `android/build.gradle`

```
allprojects {
    repositories {
        // ... your other stuff
        configurations.all {
            resolutionStrategy {
                force "com.android.support:appcompat-v7:$supportLibVersion"
            }
        }
    }
}
```

**Comment by LRNZ09** [comment]
@rgoldiez yours is the best solution I've found so far, thanks!

**Comment by edcalderin** [comment]
> configurations.all {
>             resolutionStrategy {
>                 force "com.android.support:appcompat-v7:$supportLibVersion"
>             }
>         }

It worked but returned this warning:

uses unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.

**Comment by FoolCoder** [comment]
@rmilejcz    i get build failed when paste the given lines it still not working

**Comment by emilioicai** [comment]
@FoolCoder can you try with v5.0.1? it contains a fix for Android builds
