### ISSUE TITLE
Create androidx support

### ISSUE THREAD

**Issue by soumyamishra89** [react-native-community/lottie-react-native#443]
Platforms
Android

Versions

Android: compileSDK 28, buildTools 28.0.3
lottie-react-native: 2.5.11
react-native: 0.58.3

Description/Current Behaviour
I have enabled AndroidX support for my app and upon building i face the following error: 

error: package android.support.v4.view does not exist

The package should enable androidx support as it is going to be the default support library from API 28 onwards.

Expected Behaviour
App should build successfully

Steps to Reproduce
See description

**Comment by ThierryVC** [comment]
This comes down to upgrading to lottie-android to at least 2.8.0.
I tried to do this myself but it becomes more complicated than I expected.

In the mean time, I suppose changing the 8th line in 
`node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java`
from
`import android.support.v4.view.ViewCompat;` 
 to 
`import androidx.core.view.ViewCompat;`
should do the trick.

**Comment by emilioicai** [comment]
HI @ThierryVC any chance you could make a PR of your attempt to update to android 2.8.0? I'm also working on this so maybe we could benefit from each other's work.

**Comment by ThierryVC** [comment]
Sorry for the delay (and lack of talent with RN & lottie).

I simply changed the version in build.gradle file to 
`implementation 'com.airbnb.android:lottie:3.0.0-beta1'`
and then removed functions and variables about 'cacheStrategy' and 'useHardwareAcceleration' in the two files going by: src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationView*.java
but still had trouble with 
`view.setAnimation(new JsonReader(new StringReader(animationJson)));`
in LottieAnimationViewPropertyManager.java
giving me: `error: no suitable method found for setAnimation(JsonReader)`
Changing it to :
`view.setAnimation(animationJson);`
would build, but then crash when I have a Lottie View with Json.

Looking forward to see this work as it would fix a few problems with recent android versions (8.0+).

**Comment by ThierryVC** [comment]
Looking at this, I do not understand why it doesn't allow JsonReader anymore.
https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
Should it then be "translated" into an `Animation` Object ?

**Comment by ThierryVC** [comment]
To quote lottie-android's [CHANGELOG.md](https://github.com/airbnb/lottie-android/blob/master/CHANGELOG.md#270) :

### 2.7.0
**Features and Improvements**
Removed deprecated LottieCompositionFactory APIs. If you were using JsonObjects, switch to Strings (#959).

No more Json? But the [Doc](http://airbnb.io/lottie/android/android.html#loading-an-animation) seems to say we can? I'm confused.

**Comment by emilioicai** [comment]
Yeah, it's a bit confusing. I will check with the guys in lottie-android

**Comment by kdawgwilk** [comment]
This is now even more urgent since RN 0.59 has now been released which depends on supportLibVersion `28.0.0` which is now blocking any upgrades for those that depend on this lib.  I am going to take a stab at it

**Comment by kaiden-dragon** [comment]
@kdawgwilk yes I'm experiencing the same issue

**Comment by bondparkerbond** [comment]
A temporary workaround that worked for me was to add: 
`api 'com.android.support:appcompat-v7:28.0.0'` inside the dependencies section in: 
node_modules/lottie-react-native/src/android/build.gradle. 

@emilioicai Would it be helpful if I created a PR with just this fix and bump the version(not sure if bugfix version bump would be appropriate here or if it could affect other things) while larger AndroidX fixes get addressed so we can upgrade to RN 59 without needing to make changes inside our node_modules?

**Comment by emilioicai** [comment]
@bondparkerbond it would be really helpful so please. go ahead and let me know if you need any help on it.

**Comment by bondparkerbond** [comment]
> @bondparkerbond it would be really helpful so please. go ahead and let me know if you need any help on it.

I made a PR, but wasn't sure what kind of version bump this would need so I haven't bumped any versions: https://github.com/react-native-community/lottie-react-native/pull/455#issue-261347676

**Comment by jgreen210** [comment]
I'm using lottie-react-native 2.6.0 in an app (with react native 59.1). Without androidx enabled it builds. If I enable androidx, it's failing like this:

```
node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java:8: error: package android.support.v4.view does not exist
import android.support.v4.view.ViewCompat;
                              ^
node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java:118: error: cannot find symbol
> Task :lottie-react-native:compileDebugJavaWithJavac FAILED
            if (ViewCompat.isAttachedToWindow(view)) {
                ^
  symbol: variable ViewCompat

node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java:144: error: cannot find symbol
            if (ViewCompat.isAttachedToWindow(view)) {
                ^
  symbol: variable ViewCompat
```

I've got android.enableJetifier=true in gradle.properties, but it's not able to automatically fix up this code since it's just some java files in node_modules, not an aar.

Looking at this issue and the above PR, I guess that's expected.

**Comment by jgreen210** [comment]
I didn't really know anything about androidx before today, so others might be able to offer better ideas than these:

* Instead of bundling java in the node module, publish aars somewhere (allowing jetifier to fix them automatically).
* Just supporting androidx would leave behind anyone still using the support lib.
* Provide two java source trees under node_modules/ (perhaps using symlinks and/or a post install script?) and the gradle build could somehow pick the right one.
* Build an aar locally and then it can maybe get fixed up with jetifier.

**Comment by jgreen210** [comment]
Another possibility:

* Add a script to this project's repo that allows node_modules/ to be patched up to work with/without androidx enabled. Users can then choose whether to configure their app's package.json with a postinstall script that invokes your script based on whether they are using androidx or not. This project would choose whether it wants to default to support lib or androidx based on which is more popular, changing to androidx when it becomes most popular.

**Comment by ktsoukanov** [comment]
> Another possibility:
> 
> * Add a script to this project's repo that allows node_modules/ to be patched up to work with/without androidx enabled. Users can then choose whether to configure their app's package.json with a postinstall script that invokes your script based on whether they are using androidx or not. This project would choose whether it wants to default to support lib or androidx based on which is more popular, changing to androidx when it becomes most popular.

Here's one example of such script - In my case I had an issue with **react-native-gesture-handler** relying on the old android.support.v4 library while the rest of the project was configured to work with androidX.

I was able to resolve the issue by adding the following to the end of the app-level build.gradle file:

`preBuild.doFirst {
    ant.replaceregexp(match:'import android.support.v4.util.', replace:'import androidx.core.util.', flags:'g', byline:true) {
        fileset(dir: '../../node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/', includes: '*.java')
    }
}`

**Comment by ktsoukanov** [comment]
> @ktsoukanov did you manage to make thats] script work with `lottie-react-native`? I keep getting strange errors if I add it.

According to [release notes](https://github.com/react-native-community/lottie-react-native), current version of lottie should work with RN=>0.59 just fine out of the box. Most likely the errors in your build are not related to androidX.

If you still get androidX-related errors, try the following:

`preBuild.doFirst {
    ant.replaceregexp(match:'import android.support.v4.view.', replace:'import androidx.core.view.', flags:'g', byline:true) {
        fileset(dir: '../../node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/', includes: '*.java')
    }
}`

lottie, as of version 2.6.1 uses only one class from the legacy support lib: **android.support.v4.view.ViewCompat**, this script moves that import to androidX namespace.

**Comment by LRNZ09** [comment]
I have the same issue.

**Comment by bondparkerbond** [comment]
RN 59 does not enable androidX support, default androidX support is coming in RN 0.60. I think we only solved app compatibility issues for 59+, but still don't have androidX support.

**Comment by 200even** [comment]
Building on what @ktsoukanov suggested. I had luck with adding the following to my app-level build.gradle:
`subprojects {
        if (project.name.startsWith("lottie-react-native")) {
            preBuild.doFirst {
                ant.replaceregexp(match: 'import android.support.v4.view.', replace: 'import androidx.core.view.', flags: 'g', byline: true) {
                    fileset(dir: './src/main/java/com/airbnb/android/react/lottie/', includes: '*.java')
                }
            }
        }
}`

**Comment by bondparkerbond** [comment]
@200even modifying sub-projects is a good work around, but especially with RN 60 and default AndroidX support around the corner, you might want a more robust solution for Jetifying your RN Android dependencies to support AndroidX such as [this one](https://github.com/mikehardy/jetifier). It allows you to Jetify(convert) all support lib dependencies into AndroidX dependencies and also allows going in reverse if you have a library that has already migrated and you're not ready to do so. It also works on npm dependencies and not just .arr files like the original Android Jetifier tool did.

**Comment by shouhuori** [comment]
Use this [script](https://gist.github.com/dudeinthemirror/cb4942e0ee5c3df0fcb678d1798e1d4d)  migrate to androidx.

**Comment by mazenchami** [comment]
this script worked for me: [jetifier](https://github.com/mikehardy/jetifier#readme)

**Comment by brenohq** [comment]
> this script worked for me: [jetifier](https://github.com/mikehardy/jetifier#readme)

which script @mazenchami ? the script that @shouhuori posted?

**Comment by mazenchami** [comment]
@brenohq not the one @shouhuori posted, its using the jetifier library...

```
1 .Convert your app to AndroidX via the [standard AndroidX migration](https://developer.android.com/jetpack/androidx/migrate)
2. npm install --save-dev jetifier
3. npx jetify
4. npx react-native run-android (your app should correctly compile and work)
5. Call npx jetify run in the postinstall target of your package.json (Any time your dependencies update you have to jetify again)
```
