### ISSUE TITLE
Animation not showing, lottie-react-native

### ISSUE THREAD

**Issue by Adokiye** [react-native-community/lottie-react-native#445]
### Description

I have a react-native view which has a lottie animation in it, but the lottie animation doesn't show at all, the screen is just yellow(background color of the enclosing view), please what may be wrong, below is my code

```      
import React, { Component } from 'react';
import {
StyleSheet,
View, 
} from 'react-native';
import LottieView from 'lottie-react-native';
export default class Splash extends Component {
constructor(props) {
super(props);
}
static navigationOptions = {
header: null,
};
render() {
return (
<View style={{flex: 1, backgroundColor: 'yellow'}}>
   <LottieView
   style={{flex: 1}}
    source={require('../check.json')}
    autoPlay
    loop
  />
  </View>
  );
    ` }}`
```
**Expected behavior:**The Animation is meant to play normally

**Actual behavior:** The animation doesn't show at all

### Versions

    "lottie-react-native": "2.3.2",
    "react": "16.3.0-alpha.0",
    "react-native": "0.55.0",

**Comment by emilioicai** [comment]
@Adokiye can you try with an animation from https://lottiefiles.com/featured ? I would like to make sure the problem is with your lottie installation and not with the animation itself

**Comment by Adokiye** [comment]
@emilioicai I got an animation from https://lottiefiles.com/featured  and used it doesn't work, and my `lottie-react-native` installed without any errors,
 "lottie-react-native": "2.3.2",
"react": "16.3.0-alpha.0",
"react-native": "0.55.0",

**Comment by emilioicai** [comment]
@Adokiye can you try giving the view and the lottieView a fixed width and height?

**Comment by ThierryVC** [comment]
simple but:
Any message in the console? in Logcat?
Are you sure your require actually gives you the Json. try logging the result
Try changing the style of the LottieView to { width: 100, height: 100 }

**Comment by Adokiye** [comment]
I have set the height and width of the LottieView and the enclosing view, it doesn't still work
  `render() {`
    `return (`
    `<View style={{width: 400,height: 400, backgroundColor: 'blue'}}>`
       `<LottieView`
       `style={{`
              `width: 400,`
              `height: 400,`
           ` }}`
        `source={require('../check.json')}`
        `loop={true}`
        `speed={1}`
     ` />`
      `</View>`
    `);`
  `}`

**Comment by lucianlature** [comment]
Had the same problem this morning, but I followed instructions from hhttps://github.com/react-native-community/lottie-react-native/issues/177#issuecomment-374908415 and it fixed the issue for me.

**Comment by arnoldc** [comment]
same problem too, with  can someone confirm , im not sure if this is issue is just me and OP, 

thanks



have this version in package.json,
 "lottie-react-native": "^2.5.11",
  "react": "16.6.3",
  "react-native": "0.58.5"

**Comment by Adokiye** [comment]
I had to add progress to the Lottie component before it worked and animated it with Animated.timing

  constructor(props) {
    super(props);
    this.progress1 = new Animated.Value(0);
    this.state = {
      progress: new Animated.Value(0),
    };
  }
  componentDidMount() {
      this.load()
    Animated.timing(this.state.progress, {
      toValue: 1,
      duration: 4000,
      easing: Easing.linear,
    }).start();
    
  }
  load(){
    this.progress1.setValue(0);
    Animated.timing(this.progress1, {
        toValue: 1,
        duration: 2000,
        easing: Easing.linear,
      }).start(()=> this.load());
  }
    render() {
        return (
            <View style={{flex: 1}}>
            <StatusBar backgroundColor='transparent' translucent={true} barStyle='light-content'/>
            <ImageBackground resizeMode={'cover'} style={{
                width: '100%',
                height: '100%',
            }} source={require('../bg.png')}>
            <LottieView source={require('../data.json')} 
      progress={this.state.progress}
      imageAssetsFolder='lottie/images' 
      />
      <LottieView source={require('../load.json')} 
      progress={this.progress1}
      style={{position: 'absolute', alignSelf: 'center', bottom: 30, width: 100, height: 100}}
      />
      </ImageBackground>
      </View>
        );
    }
}

**Comment by emilioicai** [comment]
@Adokiye so you mean autoPlay was not working?

**Comment by Adokiye** [comment]
Yes

**Comment by Alenius** [comment]
This still does not work for me. I can see the LottieView but the animation does not start. Even with @Adokiye's tips. Anyone else?

**Comment by nicsachin** [comment]
is it working now
<LottieView style={{flex:1}} source={require('./anim')} autoplay loop/>
here is my code

**Comment by nlabofa** [comment]
anyone fixed this?

**Comment by Alenius** [comment]
For me it was solved by upgrading to React 0.6

**Comment by nlabofa** [comment]
@alenius React 0.6???

**Comment by Alenius** [comment]
Oh sorry, react native of course, we are on RN 0.60.5 right now and it's working as intended

**Comment by JakeHadley** [comment]
@Alenius can you give details of versions you have and such? I'm on RN 60 as well and the animation is not showing up at all.

**Comment by Alenius** [comment]
```
"lottie-ios": "3.0.3",
"lottie-react-native": "3.1.0",
"react-native": "0.60.5"
```

As soon as I updated to 0.6 it worked fine for me.

**Comment by JakeHadley** [comment]
Do you have an entry in your podfile?

**Comment by Alenius** [comment]
Above 0.6 the autolinking uses the `use_native_modules!`-entry in the podfile

**Comment by JakeHadley** [comment]
Oh that's right. I don't currently have that line, I probably should, yeah?

**Comment by JakeHadley** [comment]
When I add that in, i get an error
```

**Comment by MingyuJeon** [comment]
I guess this is because your lottie file size is over 100kb.
In my case, it works well after I changed smaller lottie file

**Comment by Stenbaek** [comment]
> I guess this is because your lottie file size is over 100kb.
> In my case, it works well after I changed smaller lottie file

Is this a defined max file size for lottie in react native?

**Comment by MingyuJeon** [comment]
@Stenbaek I tried to use some Lottie files which have different file size and figured out that it only makes an issue over 100kb size for Lottie files. The size might be different depends on your internet speed.

**Comment by joaonew** [comment]
Is this issue still open? Animations are showing in iOS but not in Android for me...

**Comment by joshuapinter** [comment]
## Upgrade to React Native 0.60+

We were running into the *exact* same thing as you on React Native 0.59.10. I tried to "config" our way around it but, alas, no joy. 

Instead, we went through the painstaking process of updating from 0.59.10 to 0.60.6 just to get this working and after a few days of upgrade hell, Lottie works perfectly now without any monkeying around.

You're gonna have to do it eventually, so that would be my recommendation. Two birds, one arduous stone.

**Comment by toekneema** [comment]
the animation wasn't playing for me in react native Android. I just wrapped the LottieView inside a View and it worked haha!

**Comment by ErickJ3** [comment]
Animation does not play on android, I believe this is a problem

**Comment by Jaserto** [comment]
Animation doesn't play on android. Breaks when I set autofalse.

**Comment by ErickJ3** [comment]
Coming back here to clarify where the error was.

Basically for animation to run you need to have a Wrapper/View around the LottieContent.

Use it this way:

```
<View>
   <LottieContent>
         <LottieView
              source={require('../../assets/animation/not-found.json')}
              autoPlay
              loop
          />
    </LottieContent>
</View>
```

**Comment by iambilalriaz** [comment]
pass `autoPlay` prop to `LottieView `

**Comment by imen-c** [comment]
> the animation wasn't playing for me in react native Android. I just wrapped the LottieView inside a View and it worked haha!

I did it it works for me !!!

**Comment by alexbr-alves** [comment]
Fala galera. eu estava tendo este mesmo problema com o autoplay e resolvi da seguinte forma:  
Na prop  _**duration**_ eu empreguei um estado com com um valor numerico que se atualizava alguns milisegundo depois que o componente _**Lottie**_ foi chamada usando o _**setTimeOut**_. 

exemplo: 


import React, { useEffect, useState } from "react";
import { View } from "react-native";
import Lottie from 'lottie-react-native'

export default function SplashScreen(){
    const [time, settime] = useState(3000);
    useEffect(() => {
        setTimeout(()=>{
            settime(5000)
        },200)
    }, [])

    return(
        <View style={{flex: 1}}>
             <Lottie  
                source={require("../../../assets/splash.json")}
                duration={time}
                autoPlay={true}
                loop={true}
            />
        </View>
)}

**Comment by ViniciusGabriel92** [comment]
Sharing my experience to maybe help anyone who is currently having this problem. After migrating from react-native 0.66.5 to react-native 0.72.4, I also updated lottie-react-native to version 6.2.0 (last one as of today) and after that my animations disappeared. After some tries I solved it by inserting style={{ height:250, width: 400}}. In my case I need these values.

**Comment by arnoldc** [comment]
@ViniciusGabriel92  I think this is because they remove the default styling at V6,
https://github.com/lottie-react-native/lottie-react-native/releases/tag/v6.0.0 , see breaking changes section

**Comment by levisstrauss** [comment]
After spending some time fixing this, mine started working.
Description:
import LottieView from "lottie-react-native";

LottieView code structure:

<LottieView
   style={{
     width: 400,
     height: 400,
   }}
   source={require("../../assets/lottie-checked-done.json")}
   autoPlay={false}
   loop={false}
   ref={animation => {
     // @ts-ignore
     this.animation = animation;
   }}
 />
 
 Activate the animation in componentDidMount:
 
 
  componentDidMount() {
    // @ts-ignore
   this.animation.play();
  }
  
 NB: Make sure to give some style to your LottieView such width and height.
 
 Learn more here: https://github.com/lottie-react-native/lottie-react-native

**Comment by hemath1001** [comment]
> After spending some time fixing this, mine started working. Description: import LottieView from "lottie-react-native";
> 
> LottieView code structure:
> 
> <LottieView style={{ width: 400, height: 400, }} source={require("../../assets/lottie-checked-done.json")} autoPlay={false} loop={false} ref={animation => { // @ts-ignore this.animation = animation; }} />
> 
> Activate the animation in componentDidMount:
> 
> componentDidMount() { // @ts-ignore this.animation.play(); }
> 
> NB: Make sure to give some style to your LottieView such width and height.
> 
> Learn more here: https://github.com/lottie-react-native/lottie-react-native

It works! Thanks sooooo much.
