### ISSUE TITLE
Change animation source breaks on iOS

### ISSUE THREAD

**Issue by carmenchapa** [react-native-community/lottie-react-native#447]
### Description

Changing the animation json file via setState works on Android but doesn't show from the second animation onwards on iOS

### Steps to Reproduce

1. I have a Lottie container with `source={this.state.animation}` which is null when the component renders.
2. Based on props I receive I set the state this one animation or another. This happens several times

**Expected behavior:**
I expect the animation to change from one to another when this props change. This works perfectly on Android

**Actual behavior:** 
On iOS the animation appears the first time (when `this.state.animation` changes from `null` to an animation) but stays white after the second change to another animation

### Versions

I'm using expo.
In my package.json: 
```
"expo": "^29.0.0",
"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
...
```

**Comment by thatgriffith** [comment]
@carmenchapa did you find a solution for this?
