### ISSUE TITLE
Cannot build Android Project

### ISSUE THREAD

**Issue by faycito** [react-native-community/lottie-react-native#448]
### Description
i tried to use lottie but i just use react-native run-android and console shows this:

* What went wrong:
A problem occurred evaluating project ':lottie-react-native'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.D
efaultDependencyHandler.

  compileSdkVersion safeExtGet('compileSdkVersion', 26)
  buildToolsVersion safeExtGet('buildToolsVersion', '26.0.3')

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

dependencies {
  compileOnly "com.facebook.react:react-native:+"
  implementation 'com.airbnb.android:lottie:2.5.6'
}

### Steps to Reproduce

1. npm install --save lottie-react-native
2. react-native link lottie-react-native
3. react-native run-android

**Expected behavior:** try to use lottie

**Actual behavior:** error ):

### Versions
    "react-native": "0.55.4",
    "lottie-react-native": "^2.5.11",

**Comment by emilioicai** [comment]
hey @faycito, can you check with the latest version?

**Comment by YogeshYo** [comment]
Any luck on this as I am facing the same issue?

**Comment by faycito** [comment]
i update the RN framework and it build ok!
