### ISSUE TITLE
JSON not working on Android

### ISSUE THREAD

**Issue by topdev531** [react-native-community/lottie-react-native#451]
I made after effect file and generated html and json file using bodymovin, It works fine on ios and html but not on android.

I think something went wrong on JSON file. Could you help me to regenerate to be matched for both ios and android?

Attached file has AEP file and files I generated with bodymovin.
[final icons animation.zip](https://github.com/react-native-community/lottie-react-native/files/2937138/final.icons.animation.zip)

**Comment by avinashlng1080** [comment]
[tree.txt](https://github.com/react-native-community/lottie-react-native/files/3224804/tree.txt)
I also encounter this issue with the attached json.
Can anyone please help ?
