### ISSUE TITLE
Certain (background) animations don't work on Android

### ISSUE THREAD

**Issue by ananyacleetus** [react-native-community/lottie-react-native#456]
I have 5 animations in my app and only 3 of them seem to be working. The ones used as background animations aren't working, but all animations are directly from http://lottiefiles.com (aka I didn't make them myself). The app works fine on iOS; this problem is Android only. I have been getting warning messages about native driver issues but not sure if that's related 

Thanks

**Comment by vgm8** [comment]
I'm having the same problem, any solution?

**Comment by bondparkerbond** [comment]
Some people have been having problems with lottie-android 2.6.0, maybe try out 
implementation 'com.airbnb.android:lottie:2.5.6' inside android/app/build.gradle in the dependencies section if you're on a lottie version that uses lottie android 2.6 if not, it may be a different issue.

**Comment by ananyacleetus** [comment]
@bondparkerbond I've been using 2.5.6

**Comment by emilioicai** [comment]
@ananyacleetus which version of `lottie-react-native` are you using?
