### ISSUE TITLE
[iOS] Lock lottie-ios on 2.5.0 or update library to 3.x.x version

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-native-community/lottie-react-native#457]
Hi,
lottie-ios from version 3.x.x is moved to swift, as for me this dependency doesn't work with this library and I had to force 2.5.0 packages.json?

Anyone have the same issue?

**Comment by lorenc-tomasz** [comment]
https://github.com/airbnb/lottie-ios/blob/3.0.0/Documentation/MIGRATING.md

**Comment by lorenc-tomasz** [comment]
Or we can move to 2.5.3 using pods not hte 2.5.3 from npm

**Comment by lorenc-tomasz** [comment]
@emilioicai any idea?

**Comment by emilioicai** [comment]
ideally we should use 3.X.X but it's not going to be an easy task so we should lock it to 2.5.3 while we prepare `lottie-react-native` for it. Are you up for submitting a PR maybe?

**Comment by lorenc-tomasz** [comment]
PR: https://github.com/react-native-community/lottie-react-native/pull/459

**Comment by alextes** [comment]
Can you be a bit more descriptive about the errors one can expect? I think it's this libraries latest version breaking our build but it's hard to tell between the caching, and hard to revert changes. I'm seeing seemingly random missing headers pop-up with React Native 0.59 and lottie. Alone, React Native, React, and even the libaries triggering the missing headers build fine. Seems like dependencies are not being caught and wrong things built in parallel.

**Comment by lorenc-tomasz** [comment]
iOS SDK locked on 2.5.0
