### ISSUE TITLE
Using two LottieViews on one screen, only one jsonData appears.

### ISSUE THREAD

**Issue by khjde1207** [react-native-community/lottie-react-native#460]
![ezgif-3-ffa6e99f7e6c](https://user-images.githubusercontent.com/18232924/55141787-80ca9500-517e-11e9-90de-3f5a10a77174.gif)

### Description

Using two LottieViews on one screen, only one jsonData appears.

### Steps to Reproduce

1. react-native init test
2. cd test && npm i 
3. npm i --save lottie-react-native
react-native link lottie-ios
react-native link lottie-react-native
add two json data . 

writing app.js  : 
```
const searchBarData = require('./res/SearchBar.json');
const checkBoxData = require('./res/CheckBox.json');
type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <LottieView   source={checkBoxData}  style={{ width : "100%" , height :100}}  autoPlay /> 
        <LottieView   source={searchBarData} style={{ width : "100%" , height :100}}  autoPlay />
      </View>
    );
  }
}
```

an easier way =============== 

git clone https://github.com/khjde1207/lottietest

cd lottietest 

npm i 

react-native run-android 

Thank you! 

**Expected behavior:** 
It's a checkbox at the top and a search bike at the bottom. 

**Actual behavior:**
Both come with check boxes.
(There are times when reloading comes out well.)

### Versions

{ lottietest: '0.0.1',
  npm: '6.9.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.12.0',
  openssl: '1.0.2p',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.2',
  v8: '6.2.414.66',
  zlib: '1.2.11' }

  "dependencies": {
    "lottie-react-native": "^2.6.0",
    "react": "16.8.3",
    "react-native": "0.59.2"
  },

**Comment by farshidshahmoradi1996** [comment]
I have same issue when i using react-native-app-intro-slider :|

**Comment by oleh-mryhlod** [comment]
Seems the issue has been fixed in the 2.6.1 version

**Comment by lorenc-tomasz** [comment]
Probably issue connected with lottie android version >= 2.6.x on 2.6.1 it was reverted to 2.5.x

**Comment by khjde1207** [comment]
I've confirmed it's been fixed. 
Thank you so much.

**Comment by lorenc-tomasz** [comment]
@emilioicai It looks like the problem is connected with lottie 2.6.x. but I have no idea why it happens.

**Comment by emilioicai** [comment]
@lorenc-tomasz I think you are right, I'll check with the guys maintaining `lottie-android`

**Comment by lorenc-tomasz** [comment]
Thank you :)

**Comment by anniewey** [comment]
Upgrade to `lottie-react-native: 2.6.1` and revert to `com.airbnb.android:lottie:2.5.6` fixed the problem. Thanks!
