### ISSUE TITLE
this.animation.play() is undefined

### ISSUE THREAD

**Issue by mikeKane** [react-native-community/lottie-react-native#461]
### Description
I'm following the api docs on how to start my animation but an error pops up. 

Undefined is not an object. (this.animation.play)

[Description of the bug]

### Steps to Reproduce

1. import LottieView from 'lottie-react-native';
2. In render add  ```<LottieView onPress={this.switchTapped}  source={require('./SWITCH.json')} autoSize={true}/> ```

3.  inside of componentDidMount() 
     ``` this.animation.play();```

**Expected behavior:** [What you expected to happen]
I expected the animation to play

**Actual behavior:** [What actually happened]
The app crashed with a TypeError: undefined is not an object (evaluating 'this.animation.play')

### Versions

``` { myApp: '0.0.1',
  npm: '6.4.1',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.3',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.51',
  zlib: '1.2.11' } ```


I've read the previous issue. I am new to react and don't quite understand how it's not a Lottie issues if I'm following the docs on how to set it up. 

I really appreciate any help. The end goal is to have the animation move to different frames based on a state change. 

Thanks,

**Comment by nescroft** [comment]
try:
 setTimeout(() => {
    this.animation.play();
  }, 200);
