### ISSUE TITLE
Android force closed when Lottie read JSON that exported/rendered from Bodymovin v5.5.0

### ISSUE THREAD

**Issue by vivevio** [react-native-community/lottie-react-native#462]
Just updated my Bodymovin plugin to `v5.5.0` from https://aescripts.com.
When my app read the JSON, The app going force closed. I thought that come from my code, but after I tried to read JSON file that exported from Bodymovin `v5.4.2` it's running normally.

Is there any of you have an issue like this one?

Here the JSON file that I tried to read.
[data.json](https://drive.google.com/file/d/1qImm_iqhBFezuQa2LBBardPCdSXzgXd6/view?usp=sharing)

**Comment by Ice-MT** [comment]
I have the same problem，the file works fine on iOS and will crash on android

**Comment by mjmasn** [comment]
Ditto. Exports from bodymovin plugin 5.4.4 and below work fine. Exports from 5.5.0+ crash the app (exception thrown is: `java.lang.IllegalStateException: Missing values for keyframe`).

**Comment by hongsa** [comment]
I have the same problem. How to downgrade bodymovin??????
Please help me..

**Comment by mjmasn** [comment]
@hongsa older versions can be downloaded from the lottie-web repo:

e.g. https://github.com/airbnb/lottie-web/blob/v5.4.4/build/extension/bodymovin.zxp

Clicking `Tag: v.5.4.4` then `Tags` will allow you to select a specific version if necessary.

Click download on the right hand side to download the zxp file.

I've never actually installed an adobe plugin but as far as I know you just double click the file on Windows, or use ZXP Installer on Mac. After our designers installed v5.4.4 the problems were solved.

**Comment by hongsa** [comment]
@mjmasn Thank you
I find bodymovin config in advanced.
It can export old version json format.

**Comment by mjmasn** [comment]
@hongsa ah interesting, I'll pass on that info. I did ask if they could find an option to change the output version but was told no 😅

**Comment by evanjmg** [comment]
@mjmasn thanks for the workaround.

So now, we need a PR to upgrade to android to this (https://github.com/airbnb/lottie-android/releases/tag/v3.0.0)

There is this but it's outdated - https://github.com/react-native-community/lottie-react-native/pull/452

**Comment by janet-rivas** [comment]
Thank for your comments, yes react native is not ready for Bodymovin V5.5.5 yet, I'm having the same issue and I found this old Animation to test on Android using lottie react native V2.6.1 and works perfect 
https://github.com/spemer/lottie-animations-json/blob/master/ic_fav/ic_fav.json
