### ISSUE TITLE
[Android] Animations disappear in FlatList

### ISSUE THREAD

**Issue by CptFabulouso** [react-native-community/lottie-react-native#465]
### Description

I have some animations in FlatList and when I scroll, the animation in row that gets out of view bounds disappears.
When I set `removeClippedSubviews={false}` on FlatList, animations stay, but performance suffers.
Happens only on android, iOS works fine
Tried both declarative and imperative implementations.

### Code

```
const data = new Array(100).fill(1);
class Test extends Component<Props, State> {
	renderTile() {
		return (
			<View style={{ height: 100 }}>
				<LottieView
					source={require('../../assets/animations/anim/data.json')}
					autoPlay
					loop
					imageAssetsFolder="images/anim"
				/>
			</View>
		);
	}

	render() {
		return (
			<FlatList
				renderItem={this.renderTile}
				data={data}
				keyExtractor={(item, index) => '' + index}
			/>
		);
	}
}
```

### Versions
"react": "16.8.3",
"react-native": "0.59.2",
"lottie-react-native": "^2.6.1",

running on device Nexus 5x - Android 8.1.0

**Comment by tonwe** [comment]
+1
