### ISSUE TITLE
Has lottie-ios dependency been accidentally downgraded from 2.5.3 to 2.5.0?

### ISSUE THREAD

**Issue by jgreen210** [react-native-community/lottie-react-native#466]
### Description

The aim of the following issue was to prevent use of lottie-ios 3.x.x (since it uses swift, and that doesn't work yet), but as a side effect the lottie-ios dependency was downgraded from 2.5.3 to 2.5.0. It's not clear if it was done on purpose or not.  This was in lottie-react-native 2.6.1.

I asked the same question here first:

https://github.com/react-native-community/lottie-react-native/issues/457#issuecomment-481288366

> Hi @lorenc-tomasz,
>
> I'm looking at:
> 
> e559561 / #459
>
> ...and trying to understand:
> 
> Why did you use 2.5.0 when there's a 2.5.3 available?
> Why did you use a version range for the podspec, but a specific version in package.json?
> 
> The answer to the first question might be: airbnb/lottie-ios#812
>
> https://guides.cocoapods.org/syntax/podspec.html#dependency documents the cocoapods version range syntax.

### Versions

lottie-react-native 2.6.1

**Comment by emilioicai** [comment]
Hi @jgreen210 , yes, 2.5.3 was throwing some compilation errors so we decided to lock the dependency on 2.5.0 until there's a solution for 3.x.x Is this creating any trouble for you?

**Comment by jgreen210** [comment]
Nothing specific, I'm just twitchy about downgrading lottie-ios for no reason. Since there is a reason, I'll close this ticket and the PR.

(I gave the version of lottie-react-native in the PR some light testing in our app - it compiled and seemed to work.)
