### ISSUE TITLE
Lottie slowing Android cold boot time by 2 seconds

### ISSUE THREAD

**Issue by djendacott** [react-native-community/lottie-react-native#469]
We've discovered that installing lottie-react-native reduces our app's startup time (cold boot) on Android by roughly 2 seconds.

iOS works fine, this is happening only on Android.

Has anyone else experienced this? If so, is it possible to resolve, or at least optimize?

**Comment by emilioicai** [comment]
I never heard of any issue like this. Can you share some code of how you integrate Lottie on Android?

**Comment by djendacott** [comment]
We have discovered this is related to png images referenced in our lottie json files. If we remove the linked image assets, our load time returns to normal. 

Is there any way to lazy load these files? Or any other way to keep them without making our cold boot suffer?

**Comment by emilioicai** [comment]
does this still happen if you keep your lottieView unmounted?
