### ISSUE TITLE
Lottie iOS does not support provisioning profiles

### ISSUE THREAD

**Issue by antonellil** [react-native-community/lottie-react-native#470]
### Description

Have a RN app and followed the instructions to install and link Lottie. It runs and builds as expected locally, and runs on device as expected locally with provisioning profiles specified locally.

However, it's hitting this xcodebuild error regarding provisioning profiles while running through our CI. Any ideas why Lottie_iOS cares about provisioning profiles in the first place and what might be the cause of this issue?

=== BUILD TARGET Lottie_iOS OF PROJECT Lottie WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
Code Signing Error: Lottie_iOS does not support provisioning profiles. Lottie_iOS does not support provisioning profiles, but provisioning profile XXXXX Development has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

** BUILD FAILED **

**Comment by RikNieuwoudt** [comment]
I'm having the same issue, any feedback?

**Comment by kidasovmercury** [comment]
Having same issue
