### ISSUE TITLE
2.5.0 lottie-ios has bugs, can we upgrade to 2.5.2?

### ISSUE THREAD

**Issue by hemster** [react-native-community/lottie-react-native#472]
Hey guys, our project has already used 2.5.2 lottie-ios, but in order to use lottie-react-native, we have to downgrade our lottie-ios to 2.5.0. However, after the downgrade, our animation stop auto-playing. We are still working on why this is happening,  in the meanwhile, I just wondering could why we have to lock lottie-ios to 2.5.0?

**Comment by hemster** [comment]
The bug caused lottie-ios in swift code not playing.

**Comment by hemster** [comment]
After replacing `LOTAnimationView` the lottie-ios

**Comment by emilioicai** [comment]
Hey @hemster , this is the relevant discussion: https://github.com/react-native-community/lottie-react-native/issues/457

**Comment by hemster** [comment]
Hey @emilioicai , thanks for responding. I'm bit lost when reading https://github.com/react-native-community/lottie-react-native/issues/457, does it mean only 2.5.3 will cause some compile error? Could we upgrade to 2.5.2?

**Comment by hemster** [comment]
And I just forked and upgraded it to 2.5.2 in the example project, it works fine. That's why I'm a bit confusing on what is the issue. https://github.com/hemster/lottie-react-native/tree/upgrade-lottie-ios

**Comment by emilioicai** [comment]
Can you try with 2.5.3? I would like to make sure https://github.com/react-native-community/lottie-react-native/issues/457 was a problem for everyone

**Comment by emilioicai** [comment]
I'm open to upgrade to 2.5.2 if we make sure it was a localised issue

**Comment by hemster** [comment]
Let me try it.

**Comment by hemster** [comment]
2.5.3 works fine.

**Comment by hemster** [comment]
https://github.com/hemster/lottie-react-native/tree/upgrade-lottie-ios here is the branch

**Comment by emilioicai** [comment]
ok, then let me check with the guy who reported the issue to realise what's going on

**Comment by hemster** [comment]
Awesome, thanks!

**Comment by tonyxiao** [comment]
I'm noticing that resizeMode doesn't work at all in latest version of lottie react native. @hemster was this the issue you were referring to?
