### ISSUE TITLE
ANR errors on Huawei devices

### ISSUE THREAD

**Issue by ywongweb** [react-native-community/lottie-react-native#477]
### Description
Update: 
So far all crashes seems to be Huawei devices, this is might be Huawei problem. Investigating...

Added Lottie animations in my app and receiving ANR error reports on Huawei devices. 

Huawei
model: WAS-LX1
"androidApiLevel": "26",
"osBuild": "WAS-LX1 8.0.0.383(C432)"

Huawei
BLA-L09
osVersion: 9
"osBuild": "BLA-L09 9.0.0.203(C432E4R1P11)"

Huawei
osVersion: 8.1.0
model: JSN-L21
"osBuild": "JSN-L21 8.2.0.135(C432)"

### Stacktrace
ANR Application did not respond for at least 5000 ms 
    Binder.java:-2 android.os.BinderProxy.transactNative
    Binder.java:1147 android.os.BinderProxy.transact
    IActivityManager.java:9832 android.app.IActivityManager$Stub$Proxy.waitForNetworkStateUpdate
    ActivityThread.java:3370 android.app.ActivityThread.checkAndBlockForNetworkAccess
    ActivityThread.java:4263 android.app.ActivityThread.performResumeActivity
    ActivityThread.java:4330 android.app.ActivityThread.handleResumeActivity
    ResumeActivityItem.java:51 android.app.servertransaction.ResumeActivityItem.execute
    TransactionExecutor.java:145 android.app.servertransaction.TransactionExecutor.executeLifecycleState
    TransactionExecutor.java:70 android.app.servertransaction.TransactionExecutor.execute
    ActivityThread.java:2123 android.app.ActivityThread$H.handleMessage
    Handler.java:109 android.os.Handler.dispatchMessage
    Looper.java:207 android.os.Looper.loop
    ActivityThread.java:7470 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:524 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:958 com.android.internal.os.ZygoteInit.main

### Versions

    "react-native": "0.59.5",
    "lottie-react-native": "2.6.1",

**Comment by fiv** [comment]
We are also experiencing similar issues. Our app has few Lottie animations & we get similar ANRs only for Huawei phones.  

```
"react-native": "0.59.4",
"lottie-react-native": "2.6.1",
```

**Comment by Freddy03h** [comment]
Hello, I've got this issue on Huawei devices as well since RN `0.59.5` but I don't use Lottie in my app. I comment here because it's the only issue I found about it concerning react-native.

**Comment by cjcheshire** [comment]
Same as @Freddy03h, I wonder if Huawei devices got an update?

**Comment by ywongweb** [comment]
I started getting ANRs after updating or adding the following libs. Anyone else did a similar update?

**Added**
"react-native-gesture-handler": "~1.0.14",
"react-navigation": "^3.4.1",
"react-navigation-fluid-transitions": "^0.3.1",

**Updated:**
"react-native-animatable": "1.3.2",
"react": "16.8.3",
"react-native": "0.59.5",
"react-native-navigation": "2.18.1",

**Comment by Freddy03h** [comment]
@ywongweb I also upgrade some of the mentioned libraries.

- `react-navigation` : `3.3.2` > `3.9.1`
- `react-native-gesture-handler` : `1.0.16` > `1.1.0`
- `react-native-reanimated` : `1.0.0-alpha.12` > `1.0.1`

(I don't use `react-navigation-fluid-transitions` or `react-native-animatable`)

I also upgrade `react-native` from `0.58.5` to `0.59.5` (and `react` from `16.6.3` to `16.8.3`) but I don't think it's directly related to React Native because I don't find related issue on github.

But I also upgraded `@react-native-community/blur`, `react-native-camera`, `react-native-device-info`, `react-native-google-signin` and `react-native-quick-actions`. Did you use them ?

**Comment by ywongweb** [comment]
Thanks @Freddy03h 

There might be a chance that Lottie is not the cause of ANRs, I added a conditional check in my code to prevent Lottie animations running on Huawei device. But that didn't help. 

I do not use the other libs you mentioned except `react-native-device-info`, which I need for the manufacturer conditional check.

The main suspect here are
```
react-navigation : 3.3.2 > 3.9.1
react-native-gesture-handler : 1.0.16 > 1.1.0
react-native-reanimated : 1.0.0-alpha.12 > 1.0.1
```

I only use the above libs in a very specific part of the app. Will disable them for Huawei devices and see.

**Comment by emilioicai** [comment]
I'm pretty sure this is not an issue with Lottie so it would be great if we could move this discussion to a more relevant repo. For the time being I won't close this issue so there's some place we can discuss about it but please, let me know if you find a better place for this.

**Comment by Freddy03h** [comment]
I found an other issue here : https://github.com/bugsnag/bugsnag-android/issues/467
@ywongweb Do you track bug with bugsnag too ? Maybe it's our suspect.

**Comment by ywongweb** [comment]
@Freddy03h Thanks for the link, I am using bugsnag. Reverting it back to a version before the ANRs, fingers cross.

@emilioicai Yeah, at this point it seems very unlikely that it's a Lottie problem. Closing the for now.

**Comment by BobbyBorisov** [comment]
@ywongweb did you find what caused the problem?

**Comment by nschild** [comment]
@Freddy03h @emilioicai @BobbyBorisov @ywongweb @cjcheshire - Did this conversation migrate somewhere else? We are experiencing a major performance issue on Huawei devices as well. I have a P20 Pro to test with.

```
    "@react-native-community/async-storage": "^1.4.2",
    "@react-native-community/masked-view": "0.0.5",
    "@react-native-community/netinfo": "^3.2.0",
    "@react-native-community/viewpager": "^1.1.7",
    "@storybook/addon-knobs": "^4.1.14",
    "@storybook/addon-ondevice-knobs": "^4.1.14",
    "@storybook/react-native": "^4.1.14",
    "@taboola/react-native-taboola": "^1.0.22",
    "@types/react-native-keep-awake": "^2.0.2",
    "@types/react-native-permissions": "^1.1.1",
    "@types/react-redux": "^6.0.10",
    "@types/redux-actions": "^2.3.1",
    "@types/reselect": "^2.2.0",
    "appcenter": "1.9.0",
    "appcenter-analytics": "1.9.0",
    "appcenter-crashes": "1.9.0",
    "babel-plugin-module-alias": "^1.6.0",
    "babel-plugin-module-resolver": "^3.1.1",
    "chroma-js": "^1.4.0",
    "core-js": "^2.6.5",
    "gsap": "^2.0.2",
    "lodash": "^4.17.11",
    "metro-react-native-babel-preset": "^0.53.1",
    "moment": "^2.23.0",
    "moment-timezone": "^0.5.23",
    "patch-package": "^6.0.2",
    "react": "^16.8.3",
    "react-dom": "^16.6.1",
    "react-mixin": "^2.0.2",
    "react-native": "0.59.1",
    "react-native-actionsheet": "^2.4.2",
    "react-native-auto-height-image": "^1.0.5",
    "react-native-background-fetch": "^2.6.0",
    "react-native-circular-progress": "^1.1.0",
    "react-native-device-info": "^0.26.1",
    "react-native-fast-image": "^5.2.0",
    "react-native-firebase": "^5.2.2",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-keep-awake": "^4.0.0",
    "react-native-linear-gradient": "^2.5.3",
    "react-native-orientation": "github:macvillanda/react-native-orientation",
    "react-native-permissions": "github:kimmanuel/react-native-permissions",
    "react-native-picker-select": "^5.2.1",
    "react-native-push-notification": "3.1.2",
    "react-native-rate": "^1.1.7",
    "react-native-render-html": "^4.1.2",
    "react-native-router-flux": "^4.0.6",
    "react-native-safe-area": "^0.5.0",
    "react-native-search-filter": "^0.1.4",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-sound-player": "^0.6.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^9.0.3",
    "react-native-swipe-gestures": "^1.0.3",
    "react-native-swipeable": "^0.6.0",
    "react-native-switch-selector": "^1.1.14",
    "react-native-vector-icons": "^6.4.2",
    "react-native-webview": "5.6.2",
    "react-redux": "^5.1.1",
    "react-timer-mixin": "^0.13.4",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.4",
    "redux-promise-middleware": "^5.1.1",
    "reselect": "^4.0.0",
    "rollbar-react-native": "^0.5.0",
    "stacktrace-parser": "0.1.4",
    "tealium-react-native": "1.0.4",
    "util": "^0.12.0"
```

**Comment by soheilpro** [comment]
I also received this error in a crash report for a HUAWEI EVR-L29 device. I'm using `react-native-device-info` but not `lottie-react-native`.
