### ISSUE TITLE
lottie view get error AnimatedComponent (undefined 'Commands')

### ISSUE THREAD

**Issue by sootood** [react-native-community/lottie-react-native#480]
i used this library in RN 57 but now i  musing RN 59 and Lottieview get this error
![Screenshot_20190513-144713_Reportoo 1](https://user-images.githubusercontent.com/12680419/57614648-9a594d80-752e-11e9-8708-7130200f611f.jpg)
 i cant understand what is problem 
please help me

RN version: 0.59.8
react-navigation-version:2.18.5
platform:android
Lottie: 2.6.1

**Comment by DibPuelma** [comment]
Be sure to follow all the steps shown here: [](http://airbnb.io/lottie/#/react-native). See that every configuration file is properly set, sometimes react native link does not work perfectly. 

After that, try to uninstall and install your app again. In my case that was what solved the problem.

Good luck!
