### ISSUE TITLE
Plan for upgrading to lottie-ios 3.x

### ISSUE THREAD

**Issue by tonyxiao** [react-native-community/lottie-react-native#481]
According to https://github.com/airbnb/lottie-ios/blob/master/Documentation/MIGRATING.md, Lottie 2.x is now in maintenance mode. Is there a plan to upgrade to lottie 3.x? Are there anything preventing that from happening?

**Comment by emilioicai** [comment]
I'm working on it but I'm making very slow progress. I would appreciate some help moving forward :)

**Comment by lorenc-tomasz** [comment]
@emilioicai Maybe you can share your WiP?

**Comment by emilioicai** [comment]
I just opened a PR from @greg7gkb's fork as I feel his work is ahead of mine:

https://github.com/react-native-community/lottie-react-native/pull/485

**Comment by lorenc-tomasz** [comment]
It's android not iOS.

**Comment by emilioicai** [comment]
Ah! true, I'll remove that

**Comment by prateekkohli1989** [comment]
@emilioicai I am able to upgrade to 3.x. Since Lottie-iOS doesn't allow to load animation from JSON how would you suggest to load the lottie json in the react native app? using filePath or bundle ?

**Comment by binjospookie** [comment]
@prateekkohli1989 which way can provide better performance? filePath sounds good.

**Comment by prateekkohli1989** [comment]
@emilioicai I had raised the PR for the lottie-ios upgrade. Please review https://github.com/react-native-community/lottie-react-native/issues/481
