### ISSUE TITLE
[Request] Upgrade to lottie-android 3.x

### ISSUE THREAD

**Issue by FoodlyEric** [react-native-community/lottie-react-native#483]
current version of lottie-react-native uses lottie-android 2.5.6 which is pretty outdated. Please update to support 3.x

**Comment by emilioicai** [comment]
let's use https://github.com/react-native-community/lottie-react-native/issues/481 as the reference issue for lottie android 3

**Comment by bondparkerbond** [comment]
It may be useful to upgrade to lottie-android 3.x at the same time as migrating to AndroidX and RN 0.60+ support as part of a major version bump as it would likely be incompatible with users still on 59 and lower still using the old support library. This is likely an issue many library maintainers will be encountering in the coming weeks and more information can be found in [this issue](https://github.com/facebook/react-native/issues/23112)
