### ISSUE TITLE
onAnimationFinish gets called on looping animations

### ISSUE THREAD

**Issue by thurinus** [react-native-community/lottie-react-native#484]
### Description
I have a `LottieView` on a Component as such:
```
<LottieView
  hardwareAccelerationAndroid={true}
  source={<animation file>}
  loop={true}
  autoPlay={true}
  onAnimationFinish={this.onAnimationFinish}
/>
```
and have a callback defined as:
```
private onAnimationFinish = (isCancelled: boolean) => {
    console.log('animation finished detected with isCancelled: ' + isCancelled);
  };
```
I keep seeing the log statement appear every time the component is rendered, even though I can confirm the animation loops, and there are no extraneous calls to `reset()` or any other manual cancellations. Documentation and code comments state that `onAnimationFinish` should only "be called only when `loop` is set to false", which is inconsistent with what's observed. Am I missing something?

### Steps to Reproduce

1. Create a `LottieView` with a looping animation source, `loop = true`, and `autoPlay = true`.
2. Define a `onAnimationFinish` callback.
3. Set the callback on the LottieView's `onAnimationFinish` property.
4. Run the app, and observe that the callback is invoked, when it shouldn't be.

**Expected behavior:** onAnimationFinish should not be called on looping animations

**Actual behavior:** onAnimationFinish was called on looping animations

### Versions
2.6.1

**Comment by dmoss18** [comment]
Can confirm this happens to me as well on version `3.2.1`
