### ISSUE TITLE
 One of the two will be used. Which one is undefined.

### ISSUE THREAD

**Issue by historicvally** [react-native-community/lottie-react-native#490]
### Description

bjc[6950]: Class LOTAnimationCache is implemented in both /private/var/containers/Bundle/Application//abc.app/Frameworks/Lottie.framework/Lottie (0x103640f98) and /var/containers/Bundle/Application//abc.app/abc (0x1012671b8). One of the two will be used. Which one is undefined.

### Steps to Reproduce

lottie-react-native  2.6.1

React Native Environment Info:
    System:
      OS: macOS 10.14.4
    Binaries:
      Node: 10.15.2 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8

**Comment by xwartz** [comment]
same issue, xcode 10.2.1

**Comment by inkCrazy** [comment]
I have the same issue too.anybody have a solution?

**Comment by harrybui2804** [comment]
i have same issue after change react-native version.

**Comment by emilioicai** [comment]
does this help? https://stackoverflow.com/a/46933115/3265176

**Comment by kiarasharnk** [comment]
Try pip uninstall opencv-python, if the library that you are importing is opencv.
