### ISSUE TITLE
Can't resolve 'react-native'

### ISSUE THREAD

**Issue by akularaja** [react-native-community/lottie-react-native#492]
I have a problem with using lottie in react. I have used npm to install lottie-react-native. However, upon import I get this error:

Module not found: Can't resolve 'react-native' 

Steps I took. 
1. npm i --save lottie-react-native
2. in my Home.js file i added 
"import LottieView from 'lottie-react-native';"
3. When i save and run on localhost I get the error. 

Versions
Lottie-react-native : 6.4.1
React : 6.4.1

**Comment by iremlaya** [comment]
You should run `react-native link lottie-react-native` on your terminal. Have you read the installation guide? it says there
