### ISSUE TITLE
Unhandled JS Exception: Invalid character '\u0003' no stack

### ISSUE THREAD

**Issue by rishichawda** [react-native-community/lottie-react-native#493]
### Description

Build is successful but App crashes while running on simulator with the following error message : 

![image](https://user-images.githubusercontent.com/26366288/58435471-4cbc1380-80de-11e9-8cbe-5ff7d376aae4.png)

### Steps to Reproduce

1. `yarn add lottie-react-native`
2. `react-native link lottie-ios`
3. `react-native link lottie-react-native`
3.  Add `Lottie.framework` to embedded binaries in xcode

**Expected behavior:** App should load and show animation.

**Actual behavior:** App crashes and shows error : 
```
Unhandled JS Exception: Invalid character '\u0003' 

no stack
```

### Versions

`react-native 0.59.8`
`lottie-react-native 2.6.1`
`node 8.15.0`
`os: macOS 10.13.6`

I have followed the process given in the documentation and also tried clean build. I don't have a pod file in my project but might add one later ( if required )

**Comment by yodaheis** [comment]
I'm facing this error. Were you able to resolve it?

**Comment by rishichawda** [comment]
@yodaheis it happened due to a bad JSON file for animation. Please check if that file is a proper JSON.

**Comment by Chris-Imade** [comment]
In my case I got this: 
Invalid character '\u0003' 

no stack
no stack

I refreshed and that solved it.
