### ISSUE TITLE
Lottie not working on Android - react-native 0.60.0-rc.0

### ISSUE THREAD

**Issue by Ludus-Team** [react-native-community/lottie-react-native#495]
### Description

Lottie not working on Android - react-native 0.60.0-rc.0

### Steps to Reproduce
step 1: react-native init RN060 --version react-native@next 
step 2: yarn add lottie-react-native
step 3: react-native link lottie-react-native
step 4: react-native run-android

### Versions

{ RN060: '0.0.1',
  npm: '6.9.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.11.4',
  openssl: '1.0.2p',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.54',
  zlib: '1.2.11' }

**Comment by bondparkerbond** [comment]
If I had to guess I'd say this is probably related to AndroidX replacing the old support library in RN 0.60. More information can be found [here](https://github.com/react-native-community/discussions-and-proposals/issues/129).
