### ISSUE TITLE
Android not respecting startFrame/endFrame args in .play() method

### ISSUE THREAD

**Issue by chrisheninger** [react-native-community/lottie-react-native#505]
### Description

Android is not respecting the startFrame/endFrame args in the `.play()` method when using the imperative API.

### Steps to Reproduce

1. Create a new project using react-native-cli, add required lottie-react-native and lottie-ios dependencies and link them (or just clone my sample project - https://github.com/chrisheninger/LottieRNTest)

2. Grab a JSON file from lottiefiles.com (more keyframes = easier to see the issue) (https://lottiefiles.com/77-im-thirsty)

3. Add a LottieView to your app

```
export default class App extends Component {
  lottieRef = null;
  
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    if (this.lottieRef) this.lottieRef.play(144, 229);
  }

  render() {
    return (
      <View style={styles.container}>
        <LottieView
          autoPlay={false}
          loop={false}
          ref={lottieView => {
            this.lottieRef = lottieView;
          }}
          source={require("./thirsty.json")}
          style={{
            height: 200,
            width: 200
          }}
        />
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}
```

4. Run the project in an iOS simulator and an Android simulator

**Expected behavior:**

The app should load and play keyframes 144 to 229.

**Actual behavior:**

On iOS, the app loads and properly plays keyframes 144 to 229.
On Android, the app loads, and the LottieView plays the entire animation, ignoring the keyframes we ask it to play.

### Video

![lottie-rn-android-bug](https://user-images.githubusercontent.com/5051745/60114580-f667e200-9728-11e9-8f6b-f0af4e577c4d.gif)

### Versions

```
    "lottie-react-native": "^2.6.1",
    "react": "16.8.3",
    "react-native": "0.59.9"
```

Happy to provide any additional details / testing– I initially caught this as a bug in the app I'm building and after spending a day thinking it was my own logic– I spun up a new project to test and noticed the bug was reproducible from a fresh state.

**Comment by weareyou-laurens** [comment]
Hi @chrisheninger ,

I haven't found a decent solution for this yet, though I noticed that lottie on Android seems to take the segments into account if you give the 'play' command just a little timeout.
The following worked for us;

```
if (Platform.OS === 'android') {
	setTimeout(() => {this.lottieRef.play(144, 229)}, 10)
} else {
	this.lottieRef.play(144, 229)
}
```

I realise this is not a permanent solution, but at least this made our animation work for now.
In case you really need to get this working just like us, I hope this helps you out.

Kind regards,
Laurens

**Comment by chrisheninger** [comment]
Hey @weareyou-laurens –

Thanks for the reply– I discovered this exact workaround a couple of days ago and it totally does the trick for now.

I'm hoping that maybe knowing about the workaround can help narrow down the root of the problem– I don't have any experience on the Java/Android side of things so poking in that source code I didn't get very far.

**Comment by chrisheninger** [comment]
I can't replicate this issue any more as of lottie-react-native@3.1.0 and react-native@0.60.4

Marking as closed/resolved.
