### ISSUE TITLE
iOS doesn't build latest version 3.0.3

### ISSUE THREAD

**Issue by iagorm** [react-native-community/lottie-react-native#513]
### Description
I'm receiving an error while trying to build my project, something related to `Lottie.modulemap`.

Error:

```
fatal error: module map file '/Users/user/Library/Developer/Xcode/DerivedData/app-dzebxnujdxzfoldhzwemhljtfkye/Build/Products/Debug-iphonesimulator/lottie-ios/Lottie.modulemap' not found
```

### Steps to Reproduce

1. Install the latest dependency
2. run `react-native run-ios` or try to build in the Xcode

**Expected behavior:**
The project should build and run the app.

**Actual behavior:** [What actually happened]
Build process fails by not finding the path `lottie-ios/Lottie.modulemap`

### Versions
react-native: 0.60.3
lottie-ios: 3.0.3
lottie-react-native: 3.0.2

You can get this information from executing `npm version`.
```
{ app: '0.0.1',
  npm: '6.9.0',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.13.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.36',
  zlib: '1.2.11' }
```

**Comment by eduardoborges** [comment]
Same here

**Comment by jdnichollsc** [comment]
Same issue testing from Xcode 10.2.1:
```
fatal error: module map file '/Users/jdnichollsc/Library/Developer/Xcode/DerivedData/RandomUserMe-cnufojqquhyrpffzpfiibitosnjr/Build/Products/Debug-iphonesimulator/lottie-ios/Lottie.modulemap' not found
1 error generated.
```

**Comment by emilioicai** [comment]
Did you run yarn install lottie-ios? What about pod install? @iagorm

**Comment by emilioicai** [comment]
Actually I think the issue might be related to a specific CocoaPods version: https://github.com/airbnb/lottie-ios/issues/859

Which version of CocoaPods are you guys using? @iagorm @eduardoborges @jdnichollsc

**Comment by emilioicai** [comment]
Another thing to note from the README: 

Apps that use static Xcode project linking need to set iOS deployment version to iOS 12 or switch to CocoaPods-based linking (using frameworks) or downgrade lottie-react-native to version 2.6.1.

**Comment by jdnichollsc** [comment]
@emilioicai but how can I fix that using `Autolinking`? This is my example with this issue: https://github.com/jdnichollsc/randomuser-me

**Comment by iagorm** [comment]
@emilioicai, I'm using the latest version of cocoapod, also I saw and tried the solution you provided and nothing. I'm using RN 60 with auto link, in Android it works.

**Comment by jdnichollsc** [comment]
Wow this issue is fixed by adding a dummy `swift` file as you can see here https://github.com/react-native-community/lottie-react-native/commit/08536d5926b9e6510ba5f93bb68070981b1b8bb7#diff-04c6e90faac2675aa89e2176d2eec7d8R35, thanks @emilioicai! 👍 
```
info Launching "org.reactjs.native.example.RandomUserMe"
success Successfully launched the app on the simulator
✨  Done in 23.04s.
```
MR of my changes, check the native configuration for iOS => https://github.com/jdnichollsc/randomuser-me/commit/afa9ae04170e822e1bb625c287dbf7709fdaa959

**Comment by iagorm** [comment]
> Wow this issue is fixed by adding a dummy `swift` file as you can see here [08536d5#diff-04c6e90faac2675aa89e2176d2eec7d8R35](https://github.com/react-native-community/lottie-react-native/commit/08536d5926b9e6510ba5f93bb68070981b1b8bb7#diff-04c6e90faac2675aa89e2176d2eec7d8R35), thanks @emilioicai! 👍
> 
> ```
> info Launching "org.reactjs.native.example.RandomUserMe"
> success Successfully launched the app on the simulator
> ✨  Done in 23.04s.
> ```
> 
> MR of my changes, check the native configuration for iOS => [jdnichollsc/randomuser-me@afa9ae0](https://github.com/jdnichollsc/randomuser-me/commit/afa9ae04170e822e1bb625c287dbf7709fdaa959)

Tried what you said and now is showing two errors: 

```
<unknown>:0: error: module map file '/Users/iagor/Library/Developer/Xcode/DerivedData/app-beepyebwjkuxnzalxahdqtlfcjrb/Build/Products/Debug-iphonesimulator/lottie-ios/Lottie.modulemap' not found
<unknown>:0: error: module map file '/Users/iagor/Library/Developer/Xcode/DerivedData/app-beepyebwjkuxnzalxahdqtlfcjrb/Build/Products/Debug-iphonesimulator/lottie-ios/Lottie.modulemap' not found
2 errors generated.

<unknown>:0: error: failed to emit precompiled header '/Users/iagor/Library/Developer/Xcode/DerivedData/app-beepyebwjkuxnzalxahdqtlfcjrb/Build/Intermediates.noindex/PrecompiledHeaders/app-Bridging-Header-swift_Z53GS9WURZLO-clang_1Y5VOCRBO1JAC.pch' for bridging header '/Users/iagor/Desktop/projects/myapp/app/ios/app-Bridging-Header.h'

```

**Comment by jdnichollsc** [comment]
Check the steps and later you can build again running the `npx react-native run-ios` command https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios

**Comment by eduardoborges** [comment]
Any Solution?

**Comment by siderakis** [comment]
This worked for me

```
sudo gem install cocoapods
pod install
```

**Comment by iagorm** [comment]
@siderakis what version of your react native and cocoapods are you using?

**Comment by eduardoborges** [comment]
I found an solution on StackIOverflow:

1. Open the project and select root project folder.
2. In top menu go to `File -> New File…`
3. Select an Swift type file and rename with something else.
4. In Build Settings select the `All` tab and go to `Build Options > Always Embed Swift Standard Librearies` and set to `Yes``

Go to `ios` folder and run `pod install` if not run yet.

Just this.

**Comment by MaxToyberman** [comment]
@iagorm please show me your targets header search path and library search path

**Comment by MaxToyberman** [comment]
do you have 
```
"${PODS_CONFIGURATION_BUILD_DIR}/lottie-ios"
"${PODS_CONFIGURATION_BUILD_DIR}/lottie-react-native" 
```
in your library search paths ?

and 
`"${PODS_ROOT}/Headers/Public/lottie-react-native"`
in your Header search paths ?

**Comment by iagorm** [comment]
@MaxToyberman I will take a look on that, but I'm almost sure they are there.

**Comment by MaxToyberman** [comment]
@iagorm  you also need 
`$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)`
in your library search paths.

**Comment by eduardoborges** [comment]
> ${PODS_CONFIGURATION_BUILD_DIR}/lottie-ios

In which file?

**Comment by MelonDeng** [comment]
same issue, I've tried all the solutions above but still error :(

**Comment by scerelli** [comment]
Same here, tries everything listed here.

**Comment by iagorm** [comment]
Have included all paths and File.swift in root and still not working.

**Comment by MaxToyberman** [comment]
@iagorm you need to include the paths in your target

**Comment by brascene** [comment]
Same here, tried all suggestions but build wont go, error is: Module map file... and Failed to emit precompiled header..

**Comment by sathindukavneth** [comment]
Try updating your cocoapods framework version by `sudo gem install cocoapods`. 
I have tried above things but they didn't work for me. Then I updated my cocoapods framework to 1.7.5 and now I can `pod install`

**Comment by hexiao-o** [comment]
Same here, I tried everything listed here.

**Comment by eduardoborges** [comment]
> Same here, I tried everything listed here.

Just create a Blank Swift file on XCode. And click on the "Create Bridge Header" after this.

**Comment by MelonDeng** [comment]
I've solved this issue. If you're using `ios/{projectName}.xcodeproj` with XCode to build your project, it'll cause this error because the latest RN version is using CocoPods to manage dependencies. You should use `ios/{projectName}.xcworkspace` instead (reopen XCode - open another project - select the xcworkspace file)

**Comment by iagorm** [comment]
> I've solved this issue. If you're using `ios/{projectName}.xcodeproj` with XCode to build your project, it'll cause this error because the latest RN version is using CocoPods to manage dependencies. You should use `ios/{projectName}.xcworkspace` instead (reopen XCode - open another project - select the xcworkspace file)

@MelonDeng Your solution worked for me!

**Comment by soloscott** [comment]
- Add `$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)` to LIBRARY_SEARCH_PATH
- Upgrade cocoapods  from `1.7.4` to `1.7.5` 

This works for me

**Comment by alexgurr** [comment]
None of the solutions above work for me (paths, cocoapods versions, blank swift file).

RN 0.61.0 rc.0
Latest lottie/lottie-ios

**Comment by jdnichollsc** [comment]
Guys, do you know how to fix this error from a new iOS target (new scheme)? I'm having these errors:
```
<unknown>:0: error: module map file '/Users/jdnichollsc/Library/Developer/Xcode/DerivedData/NordstromON-eczmigddfhmorrersgnfcfyqybhr/Build/Products/Release-iphonesimulator/lottie-ios/Lottie.modulemap' not found
<unknown>:0: error: module map file '/Users/jdnichollsc/Library/Developer/Xcode/DerivedData/MyApp-eczmigddfhmorrersgnfcfyqybhr/Build/Products/Release-iphonesimulator/lottie-ios/Lottie.modulemap' not found
2 errors generated.
<unknown>:0: error: failed to emit precompiled header '/Users/jdnichollsc/Library/Developer/Xcode/DerivedData/MyApp-eczmigddfhmorrersgnfcfyqybhr/Build/Intermediates.noindex/PrecompiledHeaders/MyAppStaging-Bridging-Header-swift_16UBEPTMT31U-clang_1N8J8KAPPGZCS.pch' for bridging header '/Users/jdnichollsc/dev/bevyup/nordstrom-on-mobile-app/ios/MyAppStaging-Bridging-Header.h'
```
Thanks in advance!

**Comment by bolandrm** [comment]
I'm having the same issue, @jdnichollsc did you ever find a resolution?

**Comment by jdnichollsc** [comment]
@bolandrm linking lottie manually and also adding a swift file into the project

**Comment by devpascoe** [comment]
RN 59.10 had to downgrade to lottie-react-native 2.6.1

**Comment by mifi** [comment]
For me rebooting finally fixed the problem 😐

**Comment by maderesponsively** [comment]
This worked for me...

> If you are using CocoaPods, open yourProject.workspace instead of yourProject.xcodeproj

**Comment by Rutvik17** [comment]
I am having this build error after upgrading to `RN . 0.60.6` from `RN 0.59.10` and i have tried everything mentioned in this thread but i am still getting this error, i am not really sure. Anyone can help ?

**Comment by maderesponsively** [comment]
@Rutvik17 are you building from your projects workspace?

I'm on RN 0.61.4 and lottie ios 3.1.3 and lottie RN 3.3.2 and it's building.

**Comment by Rutvik17** [comment]
> @Rutvik17 are you building from your projects workspace?
> 
> I'm on RN 0.61.4 and lottie ios 3.1.3 and lottie RN 3.3.2 and it's building.

Yes i am building from project workspace in xcode, dont know why i am getting an error
`fatal error: module map file '/Users/rutvikpatel/Library/Developer/Xcode/DerivedData/SMB-ftywtelxmcogcnfzafbgyboiiyak/Build/Products/Release-iphonesimulator/lottie-ios/Lottie.modulemap' not found
1 error generated.`

**Comment by Rutvik17** [comment]
I solved the issue by adding Lottie_ios to schemes in xcode project.
1. Select Product
2. Schemes
3. Manages Schemes 
4. Add Lottie_IOS to schemes

**Comment by jeiemgi** [comment]
This is kind of silly, but if you are upgrading react-native and your dependencies, and you just bumped your `platform :ios, '12.0'` to XX.X make sure you have the same number as here: 

![Screen Shot 2020-04-02 at 16 46 29](https://user-images.githubusercontent.com/16458560/78306811-88dfb200-7501-11ea-84b3-f05d023f02ac.png)

General > Deployment Info > Target iPhone

I was able to build `npx react-native run-ios` but not to Product > Archive, and the error showing was this, Hope this helps someone in a future.

**Comment by 15110011** [comment]
> I've solved this issue. If you're using `ios/{projectName}.xcodeproj` with XCode to build your project, it'll cause this error because the latest RN version is using CocoPods to manage dependencies. You should use `ios/{projectName}.xcworkspace` instead (reopen XCode - open another project - select the xcworkspace file)

You save my life bro

**Comment by EdmundMai** [comment]
@jeiemgi getting the ios versions to match fixed it for me. thanks!!!!!

**Comment by Rutvik17** [comment]
This combination solved my issue
`"lottie-ios": "2.5.0",
    "lottie-react-native": "2.6.1",`

**Comment by Allmacamo** [comment]
Had the same issue on M1 Mac, @jeiemgi solution is the only one that worked for me.

**Comment by nicholasrussellweb** [comment]
Oddly, if i build with npm or xcode the project builds fine, however, when fastlane builds the project, I'm getting this error.

**Comment by Brumor** [comment]
Me to @nicholasrussellweb did you fix it?

**Comment by josueaceves** [comment]
Any fix?

**Comment by pravchuk** [comment]
Go to "File" > "Project Settings" change to "New Build System"

**Comment by MorganTrudeau** [comment]
Make sure your Podfile deployment target is the same as the target set in your xcode under General settings. 👍

**Comment by Ramesh-Chathuranga** [comment]
I also had the same issue. then i tried above mentioned solution, those are not worked for me. this was happened after library updating my React-Native project. Then i fixed my issue. i checked both podfile and Build settings ios deployment target   and  platform version. when i checked them version number of those two are differe
<img width="728" alt="Screenshot 2022-05-12 at 19 18 25" src="https://user-images.githubusercontent.com/46773056/168091570-698a8dfc-3495-4187-a11e-89ba213aa822.png">
<img width="788" alt="Screenshot 2022-05-12 at 19 18 09" src="https://user-images.githubusercontent.com/46773056/168091582-2ebde177-dc32-4f25-9011-8a89e419303b.png">
nt. then keep them in same version number and issue was fixed for me.

**Comment by ankitpunchh** [comment]
> Me to @nicholasrussellweb did you fix it?

Same for me. How did you fixed ?
