### ISSUE TITLE
Version 3.0.3 on Android, RN 0.60.0 crashes at start.

### ISSUE THREAD

**Issue by ricbermo** [react-native-community/lottie-react-native#521]
### Description

The Android application is crashing just after it starts, meaning it builds and launches successfully but nothing else.

### Steps to Reproduce

1. create a new repo
2. Install the package
3. run `react-native run-androd`

**Expected behavior:**
The app should render the animtions

**Actual behavior:**
The app crashes

**Versions:**

RN: 0.60.0
Lottie: 3.0.3

** Repo **
https://github.com/ricbermo/open-source-contrib

**Comment by sathindukavneth** [comment]
Had the same issue after updating into 3.0.3

**Comment by roninprogrammer** [comment]
Hi guys , 

I believe this is because the library didnt auto-linked properly to native code ,

In order to solve this , please add this manually: 

**MainApplication**

```
- add import com.airbnb.android.react.lottie.LottiePackage;
- add packages.add(new LottiePackage())in List<ReactPackage> getPackages();
```

**Build.gradle**
`add implementation project(':lottie-react-native')`

**Settings.gradle**
```
include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')

```

**Comment by emilioicai** [comment]
thanks a lot @roninprogrammer. That was actually the issue. I will add this to the README until autolinking is fixed.

**Comment by roninprogrammer** [comment]
> Had the same issue after updating into 3.0.3

@ricbermo @sathindukavneth you may try this manual implementation

**Comment by ricbermo** [comment]
@emilioicai @roninprogrammer thanks for your help. I can confirm that workarounds the issue.

**Comment by ifsnow** [comment]
It works well without crash in the recently updated 3.0.4

**Comment by roninprogrammer** [comment]
> It works well without crash in the recently updated 3.0.4

Awesome

**Comment by roninprogrammer** [comment]
> @emilioicai @roninprogrammer thanks for your help. I can confirm that workarounds the issue.

you may close the issue =)
