### ISSUE TITLE
Android crashes when .play() startFrame > endFrame

### ISSUE THREAD

**Issue by nebrasjemel** [react-native-community/lottie-react-native#522]
### Description

Trying to play an animation in reverse using .play(startFrame, endFrame) with startFrame>endFrame. 

**Expected behavior:** Animation plays in reverse on Android and iOS

**Actual behavior:** It plays fine on iOS. on Android the app crashes and you get (if you're playing from frame 257 to frame 241)
` E AndroidRuntime: java.lang.IllegalStateException: Frame must be [257.000000,241.000000]. It is 241.000000`
 ` 
E AndroidRuntime: 	at com.airbnb.lottie.utils.LottieValueAnimator.verifyFrame(LottieValueAnimator.java:270)
`
 ` E AndroidRuntime: 	at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:114)
`
 ` E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
`
 ` E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
`
 ` E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:655)
` 
` E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
`
 ` E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
`
 ` E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
`
 ` E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
`
 ` E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
`
 ` E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
`
 ` E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
`
 ` E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`
### Versions

lottie-react-native @2.6.4, react-native@0.59

**Comment by mayconmesquita** [comment]
This is happening here.

**Comment by calix** [comment]
Same issue...

**Comment by nebrasjemel** [comment]
For my use case, I solved the problem by interpolating an animated variable and using progress() for most use cases that should work too, but it's still an issue given that using .play() as described above works in iOS.
