### ISSUE TITLE
"TextCompositionLayer.swift" used twice IOS

### ISSUE THREAD

**Issue by LPranulis** [react-native-community/lottie-react-native#523]
Hello, I have a problem with iOS building.

> info <unknown>:0: error: filename "TextCompositionLayer.swift" used twice: '/Users/XXX/Documents/React-Native/PROJECT/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift' and '/Users/XXX/Documents/React-Native/PROJECT/node_modules/lottie-ios/lottie-swift/src/Private/LayerContainers/CompLayers/TextCompositionLayer.swift'
> 
> info <unknown>:0: note: filenames are used to distinguish private declarations with the same name
> 
> info Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

Lottie-react-native @ 3.0.3
React-native @ 0.59.8

**Comment by LPranulis** [comment]
FIXED!

Problem comes through the installation. No need to write `npm i --save lottie-ios@3.0.3` because `npm i --save lottie-react-native` package has lottie-ios package inside node_modules. Therefore, when you write `react-native link lottie-ios` it ruins and duplicates everything.

So, the installation must be (for 0.59):
1. Remove from node_modules / unlink all lottie files;
2. Write `npm i --save lottie-react-native`;
3. Go to project/node_modules/lottie-react-native/node_modules;
4. Cut lottie-ios folder and paste it into the project node_modules folder near lottie-react-native;
5. Write 
`react-native link lottie-ios
react-native link lottie-react-native`

That's it! :)

**Comment by brascene** [comment]
I'm glad for you :) 
What about 0.60> ? There's no _react-native link_, I just add the packages with yarn, pod istall, and no way to build the project.. so sad.

**Comment by emilioicai** [comment]
@brascene are you having any issues? There's no `react-native link` needed in RN 0.60

**Comment by LPranulis** [comment]
@brascene Just try to do all steps, except fifth. React-Native 0.60 has auto-linking.

**Comment by brascene** [comment]
Thank you guys for quick support, and yeah @emilioicai I have issue that I cannot build iOS project after following simple installation guide: 

1. `yarn add lottie-react-native`,
2. `yarn add lottie-ios@3.0.3`
3. `pod install`

There was like kilometer long error like nothing is working xD I've tried to delete pods, and node modules etc. but no progress still. When I run the app from terminal with _react-native run-ios_ command I get that long error, and when I run the app from XCode directly, there're two errors, one of them was `fatal error: module map file... etc.`.
Currently (after deleting and installing again, clearing derived data, pods, and node modules), now I have 100 errors (all complaining about `Undefined symbol` and many warnings related with _Could not find autolinked library_).

@LPranulis 
`lottie-ios@ ` _node_module_ is already inside project's _node_modules_, so all your steps are covered with above two commands..
I have no idea what happend the first time I added this to my project, now I can't run it even without lottie..

**Comment by emilioicai** [comment]
@brascene Not related to auto linking at all but did you try adding a swift file as suggested here? https://stackoverflow.com/a/56176956/3265176

**Comment by brascene** [comment]
I'll give it a try in a moment

**Comment by brascene** [comment]
OMG it's working :)
This is what magically make it work: 
`$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)`

I hope Android won't have similar issue.. 
Thanks again for very quick support! And thanks for Lottie!

**Comment by ganoch** [comment]
there's something in lottie-ios project under the project.pbxproj file where 
on line 639 and line 676 `TextCompositionLayer.swift` is included twice

**Comment by msqar** [comment]
@ganoch Have the same error, and how do i fix this now? :(

**Comment by msqar** [comment]
@LPranulis i don't have anything inside lottie-react-native's node_modules, it's just an empty folder. Im using RN 0.60.4 and no cocoapods. Any help?

**Comment by msqar** [comment]
I made it work, it took me so many hours but finally. Had to add some stuff on react-native-lottie

**Comment by nandha-kumar-hajari** [comment]
> OMG it's working :) #513 This is what magically make it work: `$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)`
> 
> I hope Android won't have similar issue.. Thanks again for very quick support! And thanks for Lottie!

Where should I add that??
