### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by Abhishek9634** [react-native-community/lottie-react-native#532]
Go to your ios folder and run:

**pod install**

After yarn/npm install 
Doc says pod install
but there is no pod file is present

**Comment by emilioicai** [comment]
Hi @Abhishek9634 which version of React Native are you using?

**Comment by Abhishek9634** [comment]
@emilioicai : 0.59.8

**Comment by emilioicai** [comment]
this is fixed in 3.2.1, please give it a try and let me know if this is still an issue. I will close this for the time being.
