### ISSUE TITLE
app unfortunately has stopped

### ISSUE THREAD

**Issue by teriologia** [react-native-community/lottie-react-native#533]
### Description

When I run `react-native run-android` and app build succesfully I'm getting crush on emulator or my real device 

**app unfortunately has stopped**

no build error no RN error screen just app close itself

I'm using AndoridX is this cause this error? also I'm running `npx jestify`

### Versions

    "react": "16.8.3",
    "react-native": "0.59.9",
    "jetifier": "^1.6.3",

###Update

when I delete `import LottieView from 'lottie-react-native';` every thing works perfectly

**Comment by emilioicai** [comment]
Maybe linking didn't work. You will need to make the following changes:

**android/app/src/main/java/<AppName>/MainApplication.java**

- add `import com.airbnb.android.react.lottie.LottiePackage;` on the imports section
- add `packages.add(new LottiePackage());` in `List<ReactPackage> getPackages()`;

**android/app/build.gradle**

add `implementation project(':lottie-react-native')` in the `dependencies` block

**android/settings.gradle**

add:

```
include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')

```

**Comment by teriologia** [comment]
> Maybe linking didn't work. You will need to make the following changes:
> 
> **android/app/src/main/java//MainApplication.java**
> 
> * add `import com.airbnb.android.react.lottie.LottiePackage;` on the imports section
> * add `packages.add(new LottiePackage());` in `List<ReactPackage> getPackages()`;
> 
> **android/app/build.gradle**
> 
> add `implementation project(':lottie-react-native')` in the `dependencies` block
> 
> **android/settings.gradle**
> 
> add:
> 
> ```
> include ':lottie-react-native'
> project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')
> ```

C:\Users\HP\Desktop\Burada\burada-app\node_modules\lottie-react-native\src\android\src\main\java\com\airbnb\android\react\lottie\LottieAnimationViewManager.java:
uses unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.
