### ISSUE TITLE
"publishNonDefault is deprecated and has no effect anymore. All variants are now published." Warning

### ISSUE THREAD

**Issue by cihati** [react-native-community/lottie-react-native#534]
### Description

When running `react-native android`, I see the following warning:

```
> Configure project :lottie-react-native
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
```

### Steps to Reproduce

Simply run `react-native android` in a RN repo with `lottie-react-native` dependency.

### Versions

react-native 0.59.4
lottie-react-native 2.6.1

**Comment by kiranjd** [comment]
This is happening in latest 3.0 version as well
