### ISSUE TITLE
what happen to lottie-react-native

### ISSUE THREAD

**Issue by callmejm** [react-native-community/lottie-react-native#535]
I using `react-native@0.59.10` ,feeling hopeless, cause my app need the animation to be work, however I tried latest version , or `3.0.1` or `2.5.11` also cannot work, digging the issue topic for almost few days , try to find a solution for what i facing in latest , `3.0.1` or `2.5.11` , neither one are work. I not sure this will cause until when, but I hope any guy wearing cap able to stand up and help us. Thanks

**Comment by emilioicai** [comment]
Hey @callmejm is this happening on ios? Are you sure you have the right dependencie's versions? There are a lot of changes these days on the way React Native handles module linking and it's likely the problem comes from that side.

**Comment by callmejm** [comment]
@emilioicai hi, i not testing in ios, cause i no have mac environment so far, no matter i try which version also have issue like build issue or app start will crash etc same like other people are facing

**Comment by emilioicai** [comment]
@callmejm in that case I would suggest to close this issue and move your comment to the Android crashes issue: https://github.com/react-native-community/lottie-react-native/issues/528

There are alreadu some sugestions you may try

**Comment by callmejm** [comment]
@emilioicai can i ask which version are not use for androidx ? i suspect because `react-native@0.59.10` haven't use androidx , but the latest `lottie-react-native@3.1.0` are support for androidx only

**Comment by emilioicai** [comment]
AndroidX was introduced in 3.0.3. You can use that version if you don't want to enable AndroidX in your app.

**Comment by callmejm** [comment]
![image](https://user-images.githubusercontent.com/6957533/62990614-2dcc5280-be7f-11e9-9e25-800f54757bcb.png)

@emilioicai Hi, Read.me not mention to use `3.0.3` but the latest, will this misunderstand what people need, ok even i use `3.0.3` in `react-native@0.59.10` it have the similar error
` Task :app:processDebugManifest FAILED
D:\RN\testlottie\android\app\src\debug\AndroidManifest.xml:22:18-91 Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.`

like : 

- https://github.com/react-native-community/lottie-react-native/issues/537
- https://github.com/react-native-community/lottie-react-native/issues/526

yes it is working on latest `react-native@0.60.4` , but i not willing to upgrade my whole project to use androidx, i hope that is a solution for those using `react-native@0.59.x`

**Comment by akshatraajjs** [comment]
"firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1",`"firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1","firebase": "^7.9.1",`
