### ISSUE TITLE
Build fails on Release(iOS)

### ISSUE THREAD

**Issue by jinyaoye23** [react-native-community/lottie-react-native#555]
Hi guys,

Posting here because I’ve got a similar problem. I succeeded to make lottie work on my RN project using lottie-iOS 3.0.3, lottie-react-native 3.1.0 and RN 0.59.1 on iOS in debug, but make an error in release and I’ve got the following message `clang: error: no such file or directory: '/Users/yao/Library/Developer/Xcode/DerivedData/mushroom-coqjneijosrwfjenxghsdgjizrfg/Build/Products/Release-iphonesimulator/libLottieReactNative.a'`

I don’t know why it’s doing this in release. Did you encounter this while trying to build on your side?

Thanks again guys

**Comment by fastcony** [comment]
same issue here

**Comment by binoalien** [comment]
i have the same issue

**Comment by fastcony** [comment]
I found a place you guys may need notice: @jinyaoye23 @binoalien 

Apps that use static Xcode project linking need to **set iOS deployment version to iOS 12**

I changed from 9 to 12, then build successfully.

**Comment by binoalien** [comment]
@fastcony thx this removes the issue

**Comment by jinyaoye23** [comment]
@fastcony thanks，I succeeded to make lottie work as you said
