### ISSUE TITLE
Upgrade lottie-ios dependency

### ISSUE THREAD

**Issue by janpe** [react-native-community/lottie-react-native#558]
### Description

Updating lottie-ios and lottie-react-native is currently not possible. Pod install gives ```lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.1.1, which depends on lottie-ios (~> 3.0.3)``` 

### Steps to Reproduce

1. Update lottie-ios to 3.1.3 and lottie-react-native to 3.1.1
2. Run `pod install`
3. You get error of incompatible versions.

**Expected behavior:** [What you expected to happen]

Succesfully update dependencies.

**Actual behavior:** [What actually happened]

Error of incompatible versions.

### Versions

lottie-ios to 3.1.3 and lottie-react-native to 3.1.1

**Comment by zinoviev** [comment]
Hey, folks. 3.0.3 Is 6 months old and misses tons of fixes and optimisations. Even worse - where is no npm release for compatible 3.0.7 of lottie-ios.

**Comment by Foskas** [comment]
@zinoviev what does that mean ?
@emilioicai is using lottie ios 3.1.3 not 3.0.3
