### ISSUE TITLE
Downloaded animation not running properly on iOS

### ISSUE THREAD

**Issue by kkbhav** [react-native-community/lottie-react-native#564]
### Description
Downloading animation files from the server and running them causes the animation to function weirdly. The animation runs very fast and does not loop even after setting all the props. But when we load a local animation and then replace the source with downloaded one, it works perfectly. 
This issue is not happening on android.

### Steps to Reproduce
1. Download a lottie JSON file from the server
2. read the contents of the downloaded file in memory and JSON parse it
3. set it as a source in LottieView
4. Set it to autoPlay

### Steps to make it work as expected
1. set any local lottie animation file as source 
2. wait for the component to load
3. Download a lottie JSON file from the server
4. read the contents of the downloaded file in memory and JSON parse it 
5. set it as a source in LottieView
6. Set it to autoPlay

**Expected behavior:** 
The animation should have normal speed and loop properly

**Actual behavior:** 
The animation is running very fast and not looping

### Versions
react-native: 0.60.5
lottie-react-native: 3.1.1
lottie-ios: 3.0.3
xcode: 11.0
cocoapods: 1.7.5

**Comment by mifi** [comment]
For me this is also happening with local animation, also only on iOS

**Comment by mifi** [comment]
I think I just solved it. For some reason I was calling `lottieRef.current.reset()` right before `lottieRef.current.play()` (this worked in `lottie-react-native@2.6.1` and I guess it was necessary back then.) Once i removed the reset call it seems it's working.

**Comment by mmaxacov** [comment]
I have a similar issue. Works fine in the ios simulator. On a real device, however, it runs one very fast, then stops.

**Comment by mchaelml** [comment]
same issue as @mmaxacov

**Comment by wowtrxqn** [comment]
> I have a similar issue. Works fine in the ios simulator. On a real device, however, it runs one very fast, then stops. I am using a simple lottie view with a require() for the json

both in simulator and real devices didn't work on ios

**Comment by ben54260** [comment]
I fix this problem, just because my style use 'flex: 1', after remove, it work fine
