### ISSUE TITLE
pod install fails on react-native-lottie 3.1.1 because of wrong dependency of lottie-ios 3.0.3 and not 3.1.3

### ISSUE THREAD

**Issue by msqar** [react-native-community/lottie-react-native#569]
### Description
Updated to RN 0.60.5 to 0.60.6 and also react-native-lottie & lottie-ios to their latest versions. But whenever I run pod install, it shows the following error:

```
[!] CocoaPods could not find compatible versions for pod "lottie-ios":
  In Podfile:
    lottie-ios (from `../node_modules/lottie-ios`)

    lottie-react-native (from `../node_modules/lottie-react-native`) was resolved to 3.1.1, which depends on
      lottie-ios (~> 3.0.3)
```

This wasn't happening before. I didn't even have the pod commands on my Podfile for lottie and it was linking it properly.

Does anyone know why this is happening? 

Attempted adding:
`use_modular_headers!`

Also the pod commands:
```
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
```

None worked.

EDIT: This is the error. The dependency on react-native-lottie 3.1.1 is "lottie-ios": "^3.0.3", and not on lottie-ios: 3.1.3. That's why it throws this error. So what's the next step?

### Versions
```
  npm: '6.7.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.1.1',
  modules: '67',
  napi: '4',
  nghttp2: '1.34.0',
  node: '11.10.0',
  openssl: '1.1.1a',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.26.0',
  v8: '7.0.276.38-node.17',
  zlib: '1.2.11' }
```

**Comment by tallpants** [comment]
Happening to me too, did you figure out a fix @msqar ?

**Comment by tallpants** [comment]
@msqar specifying 3.0.3 explicitly for lottie-ios seems to fix it:

`yarn add lottie-react-native lottie-ios@3.0.3`

**Comment by xuqianjin** [comment]
they forget to update npm package?

**Comment by emilioicai** [comment]
this is fixed in 3.2.1, please give it a try and let me know if this is still an issue. I will close this for the time being.

**Comment by msqar** [comment]
@emilioicai hey emilio, thanks for replying and solving this. It works like a charm now! happy week everyone!

**Comment by msqar** [comment]
@tallpants yes, i did that yesterday just to make it work, but now it's solved. You can update to latest. :D
