### ISSUE TITLE
Android crash when toast work with lottie

### ISSUE THREAD

**Issue by kangbb** [react-native-community/lottie-react-native#573]
### Description

I'm try to add lottie in a toast, and this works well in IOS, but crash in Android.

### Steps to Reproduce

What I am using:
- react-native-easy-toast. [https://github.com/crazycodeboy/react-native-easy-toast](https://github.com/crazycodeboy/react-native-easy-toast)
- lottie-react-native. [https://github.com/react-native-community/lottie-react-native/issues/new?template=bug_report.md](https://github.com/react-native-community/lottie-react-native/issues/new?template=bug_report.md)

And the code is:
```
(.show ^js @toast-ref (r/as-element [ani/toast-loading]) (.-FOREVER ^js DURATION))
```
**Expected behavior:** 
The animation work well both on Android and IOS.

**Actual behavior:** 
Android crash when I do this, and the application will be forced exit.
### Versions
- react-native: 0.59.0
- lottie-react-native: 2.6.1

**Comment by cleanDev-win** [comment]
Hello.
I am developing app using expo(expo sdk 35) and I am also using react-native-easy-toast.
On emulator, it is working well. But after releasing apk, the app crashes when showing toast.
I`d really appreciate if you find any solution for that.
Thanks again.
