### ISSUE TITLE
Text does not render on iOS

### ISSUE THREAD

**Issue by BenMansley** [react-native-community/lottie-react-native#580]
### Description

When running [this simple json](https://gist.github.com/BenMansley/dcb1c6a76b50ff7958df32705e8055fe) on iOS, the diamond shows but the text does not. It works ok on Android and web (in the [LottieFiles preview](https://lottiefiles.com/share/LjKPuR))

### Steps to Reproduce

1. Place the animation JSON into a simple `<LottieView/>`:
```js
<LottieView
  source={this.entranceAnimation}
  autoPlay={true}
  loop={false}/>
```

**Expected behavior:** The animation should show with text

**Actual behavior:** The animation plays, but the text is hidden

### Versions

`lottie-react-native`: 2.6.1
`lottie-iOS`: 2.5.0

**Comment by gziolle** [comment]
Hi @BenMansley!
Do you have any ideias about how to solve this problem?

Thanks!

**Comment by anhkieet** [comment]
I got the same issue here :( Can anyone look into this issue?

**Comment by ayberkanilatsiz** [comment]
Same issue...

Did you find any solution @anhkieet @gziolle

**Comment by thorep** [comment]
same..not text on ios..works on android

**Comment by gziolle** [comment]
Me neither. I ended up rendering texts separately.
