### ISSUE TITLE
Android App crashes at start

### ISSUE THREAD

**Issue by tobiaseisenschenk** [react-native-community/lottie-react-native#591]
### Description

After successful build and install the Android app crashes 1-2 seconds after launch. I believe the important logcat lines are:
```
11-15 18:07:46.551 15517 15517 D AndroidRuntime: Shutting down VM
11-15 18:07:46.552 15517 15517 E AndroidRuntime: FATAL EXCEPTION: main
11-15 18:07:46.552 15517 15517 E AndroidRuntime: Process: com.nui, PID: 15517
11-15 18:07:46.552 15517 15517 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setAnimationFromJson(Ljava/lang/String;Ljava/lang/String;)V in class Lcom/airbnb/lottie/LottieAnimationView; or its super classes (declaration of 'com.airbnb.lottie.LottieAnimationView' appears in /data/app/com.nui-mATE6Z4WJe42FgcSr3QCXQ==/base.apk!classes2.dex)
11-15 18:07:46.552 15517 15517 E AndroidRuntime: 	at com.airbnb.android.react.lottie.LottieAnimationViewPropertyManager.commitChanges(LottieAnimationViewPropertyManager.java:103)
```
So this might be related to #543 

### Versions

```
"react": "16.9.0",
"react-native": "0.61.4",
"lottie-ios": "^3.1.3",
"lottie-react-native": "^3.3.2",
```
I use autolinking, linking manually as suggested in the ready produced the same behavior with an additional warning.

**Comment by tobiaseisenschenk** [comment]
Actually this was solved by just manually linking the library as suggested in #521 .

**Comment by JonathanHolvey** [comment]
I'm experiencing this error as well. The manual linking described in #521 appears to be set up correctly, but the `noSuchMethodError` for `setAnimationFromJson` causes the app to crash when attempting to render a LottieView component.

What can I do to debug this issue?

I'm using the following versions:

- react-native v0.61.2
- lottie-react-native v3.0.3

**Comment by teapot2** [comment]
Life is pain
