### ISSUE TITLE
Cannot build on React Native 0.61.5

### ISSUE THREAD

**Issue by nok0620** [react-native-community/lottie-react-native#599]
Hi guys, I'm new to Lottie and have followed the instructions on the front page to install.
I'm using Mac to run the following commands,
```
npx react-native init Delta 
cd Delta
yarn add lottie-react-native
yarn add lottie-ios@3.1.3
cd ios
pod install
cd ../
npx react-native run-ios
```
and ran into the following error
```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening Delta.xcworkspace. Run CLI with --verbose
```
When I tried to build again in XCode (v11.3), the following error pops, 
Please help. Thanks.

![image](https://user-images.githubusercontent.com/57989597/71291698-4b21a800-23ae-11ea-8798-e62a81acc374.png)

**Comment by Rizaldinurm** [comment]
may related failed linking,
[try this](https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios)

**Comment by nok0620** [comment]
Tried the solutions from the link and the 3rd one (creating an empty swift file and Bridging Header) worked like a charm!
[https://stackoverflow.com/a/56176956](https://stackoverflow.com/a/56176956)
Thanks 😄

**Comment by victorkl400** [comment]
> Tried the solutions from the link and the 3rd one (creating an empty swift file and Bridging Header) worked like a charm!
> https://stackoverflow.com/a/56176956
> Thanks 😄
As you said "worked like a charm!"
