### ISSUE TITLE
No such module 'Lottie' error when building for release

### ISSUE THREAD

**Issue by azamouchi** [react-native-community/lottie-react-native#605]
### Description

I'm trying to create an archive of my app, that is using this library, when i try a simple build it passes successfully but when i try a archiving it (a release build) it fails 

### Steps to Reproduce

1 - Link the library manually to Xcode project (drag and drop **lottie-react-native** and **lottie-ios** projects from node_modules folder)
2 - Adding **libLottieReactNative.a** & lib**Lottie.a** as linked libraries to my target
3 - Archive the app

**Expected behavior:** 
The app should archive successfully 

**Actual behavior:**
The build process fails when compiling **ContainerView.swift**, it can't find the imported library Lottie int this file, though it's already linked and i have no issue when building it for debug mode

### Versions

react-native : 0.59.10
lottie-react-native : 3.0.2
lottie-ios : 3.1.5
Xcode : 10.3

<img width="1420" alt="Capture d’écran 2020-01-21 à 15 08 52" src="https://user-images.githubusercontent.com/6905567/72811976-fbf6bd80-3c60-11ea-8585-f9a2e7ab7196.png">

**Comment by Ross-Landry** [comment]
I have the same problem. Although my build fails in debug as well. Did you find a solution?

**Comment by Ross-Landry** [comment]
"react-native": "^0.59.9",
"lottie-ios": "^3.0.3",
"lottie-react-native": "^3.0.2"

**Comment by azamouchi** [comment]
Try adding the lottie library as a target dependecie in Build Phases, and do a clean build after that. This solved the issue for me

<img width="870" alt="Capture d’écran 2020-02-26 à 23 01 55" src="https://user-images.githubusercontent.com/6905567/75392642-bdea5a80-58ec-11ea-8d54-7b3017e5ed22.png">

**Comment by amiinous** [comment]
I had exactly the same issue, adding the two (LottieReactNative and LottieLibrariIOS) to Build Phases -> [Target] Dependencies fixed the issue.

> Try adding the lottie library as a target dependecie in Build Phases, and do a clean build after that. This solved the issue for me
> 
> <img alt="Capture d’écran 2020-02-26 à 23 01 55" width="870" src="https://user-images.githubusercontent.com/6905567/75392642-bdea5a80-58ec-11ea-8d54-7b3017e5ed22.png">
