### ISSUE TITLE
Unable to resolve module 'react-native-safe-module' from 'node_modules\lottie-react-native\lib\LottieView.js' react-native-safe-module could not be found within the project

### ISSUE THREAD

**Issue by sushrut-desora** [react-native-community/lottie-react-native#611]
### Description
Updated the lottie library in my react-native project from 2.6.1 to 3.3.2 using.  The project built successfully but while loading the js from metro bundler got this error. Had to install 'react-native-safe-module' manually to resolve the issue

[Description of the bug]

### Steps to Reproduce

1. ```npm i --save lottie-react-native@latest```
2.  ```react-native run-android```
3.  Build succeeds
4. Metro bundler throws the above error while loading javascript
5. To resolve the error, install 'react-native-safe-module'  manually. ```npm i --save react-native-safe-module```
6. Error is resolved and the app js loads and i am able to open the app

**Actual behavior:** [What actually happened]
Metro bundler throws the error while loading javascript

**Expected behavior:** [What you expected to happen]
Should not need to install 'react-native-safe-module' manually or should throw an error during build time instead of during js load time or atleast the repo readme should contain instructions to install the dependency

### Versions
2.6.1 -> 3.3.2

**Comment by sushrut-desora** [comment]
Needed to upgrade from 2.6.1 to 3.3.2 after ejecting from expo to bare workflow because the lottie animations were not rendering after ejection outside of expo environment. It still worked ok if i ran the ejected app in expo client. Upgrading to 3.3.2 seems to have fixed this issue.

**Comment by gemdevgit** [comment]
Hi, I am facing the same issue. I upgrade lottie-react-native to 3.3.2, after that I am facing this. Can you please help

**Comment by OscarYuen** [comment]
I meet this issue too.
I am using lottie-react-native 3.3.2 with latest expo bare workflow

**Comment by tamago3keran** [comment]
Me too. I resolved this problem by the script:tada:
Please try it ☺️

```
watchman watch-del-all;
rm -rf node_modules/*;
rm -rf $TMPDIR/react-*;
rm -rf $TMPDIR/metro-bundler-cache-*;
rm -rf $TMPDIR/metro-cache/*;
```

**Comment by tamago3keran** [comment]
@emilioicai Thank you!

**Comment by vtolochk** [comment]
`yarn add react-native-safe-module` helped me
