### ISSUE TITLE
Some frames cut off in react-native ios

### ISSUE THREAD

**Issue by MebDevelop** [react-native-community/lottie-react-native#615]
### Description

[Description of the bug]

### Steps to Reproduce

1. [First Step] 
"lottie-ios": "3.1.3",
"lottie-react-native": "^3.3.2",
2. [Second Step]
pod install
3. [and so on...]
<LottieView
          ref={animation => {
            this.animation = animation;
          }}
          source={bot}
/>

**Expected behavior:** [What you expected to happen]
https://i.imgur.com/MgTJtUw.mp4
**Actual behavior:** [What actually happened]
https://i.imgur.com/dk3YUCR.mp4
### Versions
"lottie-ios": "3.1.3",
"lottie-react-native": "^3.3.2",
You can get this information from executing `npm version`.

**Comment by Shing-Ho** [comment]
any idea?

**Comment by corosteg** [comment]
This could be due to the version of body movin you are using.
I had the same problem I downloaded the JSON of a similar animation but with a more recent bodymovin.
It worked for me

**Comment by MebDevelop** [comment]
Could you explain more about it? I am not sure the version of body movin.
So how sure I solve this?

**Comment by MebDevelop** [comment]
This is first time that using lottie and I receive json file and some images, so not sure how could I solve this problem. Please guide me.

**Comment by corosteg** [comment]
this link explains how you can use animations with assets:
https://github.com/react-native-community/lottie-react-native/blob/master/docs/api.md#using-animations-with-assets

**Comment by MebDevelop** [comment]
Thank you, I will check bodymovin version

**Comment by moniquealtero** [comment]
Any tip on this?
