### ISSUE TITLE
Setting speed doesn't seem to resume/pause the animation

### ISSUE THREAD

**Issue by guanw** [react-native-community/lottie-react-native#621]
### Description
Hi, I'm trying to use a `this.state.speed` to control the speed of animation. Notice on the documentation it says 1 as play and 0 as stop and that's what I did:
```
// will be fired by a button
onPlay = () => {
  this.setState({
    speed: 1
  });
  ...
}

// will be fired by a button
onPause = () => {
  this.setState({
    speed: 0
  });
  ...
}

...
<LottieView
  ref={animation => {
   this._animation = animation;
  }}
  resizeMode='cover'
  style={...}
  source={...}
  speed={this.state.speed}
/>
```

I notice two issue with this:
1. The onPlay won't really make the animation play unless I specifically call 
```
this._animation.play();
```
inside `onPlay`

2. The animation seems to get `reset`
```
this.setState({
  speed: 0
});
```
in `onPause` and starts from beginning after `onPlay` is fired.

Any idea why? Or is there a recommended way to pause animation with lottie? Thanks for any reply in advance.

### Versions

You can get this information from executing `npm version`.
```
lottie-react-native: 2.6.1
expo: 33.0.7
```

**Comment by albertcito** [comment]
It works for me. Look at this: https://snack.expo.io/@albertcito/example-lottie
