### ISSUE TITLE
Android animation does not play to completion

### ISSUE THREAD

**Issue by jaywayawyaj** [react-native-community/lottie-react-native#623]
### Description

Using lottie-react-native works fine with my iOS loop, but the android loop doesn't complete and so jumps. (See attached video - android on the right)

[Demo video](https://drive.google.com/file/d/1sI-n8BWFv5uNW4DM0rg2LXOk0u14Gg3c/view?usp=sharing)

Sounds related to [this fix](https://github.com/airbnb/lottie-android/pull/1126) which was released with lottie-android in version `3.0.0`. This version is what the react native lottie uses, though...

**Expected behavior:** 

Loop to be consistent and complete

**Actual behavior:** 

On Android the version skips a frame (or a few)

### Versions

lottie-react-native `3.1.0` and `3.3.0`

### Code snippet:

```
export default function LoadingLogo(props: Props) {
  const animation = useRef<LottieView>(null);

  let logo = require("../../assets/lottie/loading_spinner_positive");
  if (props.isDarkBackground) {
    logo = require("../../assets/lottie/loading_spinner_negative");
  }

  useEffect(() => {
    if (animation && animation.current) {
      animation.current.play();
    }
  }, []);

  return (
    <View
      style={{
        flex: 1,
        justifyContent: "center",
      }}
    >
      <View style={{ alignItems: "center" }}>
        <View
          style={{
            width: 60,
            height: 60,
          }}
        >
          <LottieView ref={animation} loop={true} source={logo} />
        </View>
        {props.message && (
          <Text
            margin="l 0 0 0"
            color={props.isDarkBackground ? "white" : "black"}
          >
            {props.message}
          </Text>
        )}
      </View>
    </View>
  );
}
```

**Comment by m1yon** [comment]
For other people having this problem: #651 fixed it for me.

**Comment by JehuReynoso** [comment]
> For other people having this problem: #651 fixed it for me.

I have the same problem, on android a circle animation is cutting... but in iOS the animation is complete... how did you fix it?

```
` "lottie-ios": "3.1.8",
    "lottie-react-native": "3.5.0",
    "moment-timezone": "^0.5.28",
    "react": "16.11.0",
    "react-native": "0.62.2",
`
```

**Comment by markholland** [comment]
I'm having this same issue and only just added Lottie to our project so should include the previously linked fix.
