### ISSUE TITLE
Animation does not show

### ISSUE THREAD

**Issue by pvanny1124** [react-native-community/lottie-react-native#637]
### Description

Animation is not visible/is not showing

### Steps to Reproduce

1. install lottie-ios@2.5.0
2. install lottie-react-native@2.6.1
3. use any sample JSON animation

**Expected behavior:** 
animation renders on screen

**Actual behavior:** [What actually happened]
animation was not displayed

### Versions
npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.13.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.36',
  zlib: '1.2.11' }

react native info:

System:
      OS: macOS 10.15.3
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 11.18 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.1, 27.0.3, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1

code snippet:

```js
<LottieView style={{
            position: 'absolute',
            zIndex: 100,
            top: '16%',
            left: '12%',
            height: '10%',
            width: '10%',
          }} source={NewAnimation} autoPlay loop />
```

**Comment by pvanny1124** [comment]
forgot to mention that my code runs just fun and I'm able to start up the app on IOS. I just don't see the animation that I'm using at all. I should mention that I'm also using a sample animation from Lottie files.

**Comment by pvanny1124** [comment]
I also tried installing the following versions as described in the docs for RN 0.59:

npm i --save lottie-react-native@3.0.2
npm i --save lottie-ios@3.0.3

and following the installation steps, and still nothing is showing up.

**Comment by pvanny1124** [comment]
I'm also importing `New Animation` at the top of my file like so:
```js
import NewAnimation from '../images/animations/newAnimations/19507-pc-to-phone.json';
```

**Comment by yesIamFaded** [comment]
If you are using Android just try to rebuild the app from Android Studio. Fixxed my issues I had with lottie.

**Comment by cohedz94** [comment]
you try add this on package.json 
"lottie-react-native":"git+ssh://git@gitlab.com:cohedz/lottie-react-native.git"

in podfile 
    pod 'lottie-ios', '~> 2.5.3'

    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

**Comment by pvanny1124** [comment]
I solved this by just upgrading to the latest version of React Native (0.62.2) and installing lottie-react-native and lottie-ios@3.1.3
