### ISSUE TITLE
How to load image resources on IOS

### ISSUE THREAD

**Issue by hzw0407** [react-native-community/lottie-react-native#641]
<LottieView
                        style={styles.lottieStar1}
                        ref={t => {
                            this.lottie1 = t;
                        }}
                        pointerEvent="none"
                        loop={false}
                        imageAssetsFolder={"lottie/star"}
                        source={require("../../../../resource/gifs/star/index.json")}
                    />

As used above，Imageassetsfolder can be used on Android，But Imageassetsfolder on IOS will be ignored。How to use pictures for animation on IOS？

**Comment by zhuliminl** [comment]
same question

**Comment by hzw0407** [comment]
> same question
我找到解决方法了 看你签名是中文 我就直接用中文了
<img width="916" alt="图片" src="https://user-images.githubusercontent.com/25050158/80576793-62e1fa80-8a38-11ea-816a-e4d4c55dde40.png">
这是官方文档的解决方案，就是你在Xcode的Resources中加入你所需要的图片就可以了
