### ISSUE TITLE
How to apply color to icon

### ISSUE THREAD

**Issue by Yandamuri** [react-native-community/lottie-react-native#642]
I have gone through this [issue](https://github.com/react-native-community/lottie-react-native/pull/584) which describes about coloring an icon,

    colorFilters={[{
              keypath: layer,
              color: colorHex
            }]}

I am not sure about following things here since I am very new using such a icons,

1.How to find out that how many layers are there in an icon?
2.Is there any property to set single color for whole icon? If so what is it?
Thank you.

**Comment by emilioicai** [comment]
This feature is a native one so it's better documented on `lottie-ios` and `lottie-android` (e.g. http://airbnb.io/lottie/#/ios?id=setting-dynamic-properties)

To know which "layers" an animation has you need to take a look at the AfterEffects project for that animation. In case you don't have access to it I think you can manually look for those layers inside the exported Lottie file but I don't think this would be an easy process.

**Comment by Yandamuri** [comment]
@emilioicai so, don't we have any option to set the color like `color='#1ABC9C'`

**Comment by emilioicai** [comment]
I'm afraid we don't
