### ISSUE TITLE
Animation looks different than the preview

### ISSUE THREAD

**Issue by pvanny1124** [react-native-community/lottie-react-native#643]
### Description
Animation does not play just like the original (react-native ios build).

### Steps to Reproduce
install latest versions of `lottie-ios` and `lottie-react-native` and render 
a lottie component as in the docs: 

```js
render {
return  <LottieView source={animation} autoPlay loop />;
}
```

**Expected behavior:**
Lottie plays the animation as is.

**Actual behavior:**
The animation plays but looks different than the original. (preview is here: https://lottiefiles.com/share/2Z7ryr)

actual: <img width="404" alt="Screen Shot 2020-05-01 at 4 31 32 PM" src="https://user-images.githubusercontent.com/26369185/80839461-475a2980-8bc9-11ea-806c-a2021935c1fb.png">

### Versions
lottie-react-native
lottie-ios@3.1.3

System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 359.52 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.1, 27.0.3, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python

  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

This is also happening for all other animations that we have. Any help would be greatly appreciated.

**Comment by emilioicai** [comment]
@pvanny1124 is this still happening? I noticed you managed to fix a later issue with this animation.
