### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by ebm93** [react-native-community/lottie-react-native#645]
### Description
I'm trying to control an animation following the guide described on this page, but when I add the following code, progress:
new Animated.Value(0), 

React-native throws error msg: 
"TypeError: Cannot call a class as a function"

### Steps to Reproduce

1. Add progress: new Animated.Value(0),  to class state
2. Save code
3. React native throws error

**Expected behavior:** 
No error

**Actual behavior:** 
Error thrown

### Versions
"react-native": "0.62.1",
"lottie-ios": "~3.1.3",
"lottie-react-native": "~3.3.2",

**Comment by emilioicai** [comment]
Are you sure the error is thrown on the line `new Animated.Value(0)` ? The `Animated` API belongs to React Native itself and I believe nothing has changed there.

Maybe if you share the full error and failing code I could help you further.
