### ISSUE TITLE
Animation seems fragmented and accelerated when using flexGrow (iOS only)

### ISSUE THREAD

**Issue by apetitje** [react-native-community/lottie-react-native#648]
### Description

I am using a Lottie animation in a simple page with only text elements. I've noticed that when I use a flex-grow styling, the animation isn't displayed well on iOS. It seems very accelerated and fragmented. On Android it is fine. I could easily reproduce this behavior with several animations.
Removing the flex-grow styling fixes the issue.

```js
<LottieView
  style={{
    flexGrow: 1
  }}
  autoPlay
  src={require("path/to/my/file")}
/>
```

### Steps to Reproduce

1. Add a flex-grow styling to a `LottieView`

**Expected behavior:** The animation works well on Android and iOS

**Actual behavior:** The animation isn't displayed correctly on iOS
 
### Versions
```
"react": "16.9.0",
"react-native": "0.61.4",
"lottie-ios": "3.1.3",
"lottie-react-native": "3.3.2"
```

**Comment by Mollet-Yuan** [comment]
When I use flex layout, I also got this bug, and the loop does not work too

**Comment by tamago3keran** [comment]
@apetitje @Mollet-Yuan It is fixed by v3.4.0 release.
Please try again after upgrading to v3.4.0 ☺️

```js
import React from 'react';
import LottieView from 'lottie-react-native';

export default class App extends React.Component {
  render() {
    return (
      <LottieView
        source={require('./animation.json')}
        autoPlay
        loop
        style={{flexGrow: 1}}
      />
    );
  }
}
```

|v3.3.2|v3.4.0|
|:--:|:--:|
|<img src="https://user-images.githubusercontent.com/24249859/82733315-0085cc80-9d4e-11ea-9df0-7d93e58f8f5e.gif" width=200px>|<img src="https://user-images.githubusercontent.com/24249859/82733330-0da2bb80-9d4e-11ea-865b-34af41f1f343.gif" width=200px>|

**Comment by tamago3keran** [comment]
@emilioicai Thank you for closing Issue and upgrading to `v3.4.0` :tada:

**Comment by emilioicai** [comment]
Thanks for your help closing issues @tamago3keran  :)
