### ISSUE TITLE
Crashing on Android: No virtual method setAnimationFromJson

### ISSUE THREAD

**Issue by quocb** [react-native-community/lottie-react-native#672]
### Description

Crashing on Android as soon as I navigate to a screen that has an animation. Seems like this crash should be fixed by manual linking but that doesn't fix it for me. What am I doing wrong? I've followed the steps for manually linking and I delete the app each time before doing a `react-native run-android`

I've also tried to downgrade lottie-react-native from 3.5.0 all the way down to 3.2.1

### Steps to Reproduce

1. Navigate to animation

**Expected behavior:** 

To see the animation

**Actual behavior:** 

Crash - `AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setAnimationFromJson(Ljava/lang/String;Ljava/lang/String;)V in class Lcom/airbnb/lottie/LottieAnimationView; or its super classes (declaration of 'com.airbnb.lottie.LottieAnimationView'`

### Versions

"react": "16.9.0",
"react-native": "0.61.5",
"lottie-ios": "^3.1.8",
"lottie-react-native": "^3.5.0",

**Comment by quocb** [comment]
Here is the full error if it's helpful

<img width="1396" alt="Screen Shot 2020-07-24 at 11 38 03 AM" src="https://user-images.githubusercontent.com/3606648/88424370-45f06580-cda2-11ea-9d61-ad9ea08598f4.png">

**Comment by mafiusu** [comment]
@quocb I recently got the same bug on Android. How did you fix the error/crash since you have closed the issue?
