### ISSUE TITLE
LottieView doesn't appear on iOS simulator

### ISSUE THREAD

**Issue by aelesia** [react-native-community/lottie-react-native#680]
### Description

Animation does not appear on iOS simulator, but appears on physical device

### Steps to Reproduce

1. View a page with LottieView on both iOS Simulator & physical iPhone

**Expected behavior:** [What you expected to happen]

- Animation should appear on simulator

**Actual behavior:** [What actually happened]

- LottieView does not appear at all on simulator
- LottieView appears on physical iPhone

### Versions

React Native 0.62.2
Simulator Version 11.3.1 (SimulatorApp-912.5.1 SimulatorKit-570.3 CoreSimulator-681.17.2)

```
{
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '4',
  nghttp2: '1.38.0',
  node: '12.6.0',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.30.1',
  v8: '7.5.288.22-node.14',
  zlib: '1.2.11'
}
```

**Comment by aelesia** [comment]
Issue was between the table and the chair.

**Comment by Thomaswaldick** [comment]
@aelesia What was the solution? I'm currently having issues where no animations are showing up in iOS

**Comment by aelesia** [comment]
I only refreshed my metro server but I failed to rebuild/reinstall the dependencies on iOS by running `react-native run-ios`.
